-- Real Tier 1 content for Topic I.I — The Psychology of Spending.
-- First end-to-end content load: 4 subtopics, their slides, and their questions.
-- Fixed UUIDs for topic/subtopic rows so this migration is safe to re-run
-- (slides/questions are not re-run-safe -- this is a single-shot content load,
-- same as the schema migrations before it).

-- Question ordering wasn't in the original schema; needed so a subtopic's
-- questions render in the intended sequence (Q1, Q2, Q3...).
alter table questions
  add column if not exists "order" int;

insert into topics (id, tier, "order", title, video_url)
values ('b14567dc-5f0b-4dd3-9e95-9fd54ea4c949', 1, 1, 'The Psychology of Spending', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 'b14567dc-5f0b-4dd3-9e95-9fd54ea4c949', 'How Ads Are Designed to Make You Want Things', 1),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 'b14567dc-5f0b-4dd3-9e95-9fd54ea4c949', 'Peer Pressure and "Everyone Has One"', 2),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 'b14567dc-5f0b-4dd3-9e95-9fd54ea4c949', 'Impulse Buys — Why They Happen', 3),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 'b14567dc-5f0b-4dd3-9e95-9fd54ea4c949', 'Practice: Spotting the Trick in Real Examples', 4)
on conflict (id) do nothing;

insert into slides (subtopic_id, "order", heading, body)
values
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 1, 'Count the seconds', 'Next time you see an advert for trainers or anything for that matter, count how many seconds are actually about the trainers or the product. It''s usually about three. The rest is people laughing, winning, looking like they''ve got their life together. That''s not filler. That''s the actual product being sold.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 2, 'The swap', 'Advertisers know this doesn''t work: "These shoes have good grip." And this does: "People who wear these look unstoppable." Your brain links the feeling in the ad to the object in the ad — even though the object didn''t create the feeling. There''s a name for it: emotional association.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 3, 'The four techniques', 'Almost every ad uses at least one: Aspiration — someone you''d like to be, using it (a sportsperson). Belonging — "people like you already have this" (classmates). Scarcity — "limited edition", "ends tonight". Repetition — see a brand again and again, across billboards, phones, shop windows, and you start trusting it without ever learning anything new about it. That last one is the sneakiest. Familiarity feels like quality. It isn''t.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 4, 'Your favourite creator is an advert', 'When a streamer or creator uses a product mid-video, that''s often a paid placement — sometimes worth thousands. It works better than a TV ad, because it doesn''t feel like one. You trust the person, so the trust transfers to the product. In many countries, paid posts are legally required to be labelled — "#ad", "paid partnership". The label is easy to miss. The effect works anyway.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 5, 'One question that cuts through it', 'When you suddenly want something you''d never thought about before: "What did I know about this 10 minutes ago?" If the answer is nothing — that want was manufactured, not discovered. That doesn''t mean don''t buy it. It means buy it after the feeling fades, not during.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 1, 'Actually count', 'Everyone has one? Count. In a class of 30, if six people have it, that''s 20%. But those six mention it constantly, and the other 24 say nothing at all. Nobody announces the thing they don''t own. So the percentage you''re seeing is broken.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 2, 'Why it feels urgent, not mild', 'Wanting to fit in isn''t shallow. It''s one of the oldest instincts you have. For most of human history, being pushed out of your group was genuinely dangerous. Your brain still treats social exclusion as a threat — which is why being the only one without something feels physically uncomfortable, not just slightly annoying. Knowing that makes it easier to sit with the feeling instead of spending money to switch it off.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 3, 'The bit nobody counts', 'Say you spend £20 matching a trend — money you''d been saving for something else. You didn''t pay £20. You paid £20 plus the thing you gave up. Economists call that second part opportunity cost, and it''s the cost people forget almost every time.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 4, 'Trends move faster than money', 'The thing everyone must have in October is often forgotten by February. The £20 doesn''t come back in February.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 5, 'The invisibility test', '"Would I still want this if I could never tell anyone I had it?" Clear yes → genuine want. Buy it if you can afford it, no guilt. Honest "not really" → what you want isn''t the object. It''s how having it makes you look. That''s still a real feeling. It''s just usually available cheaper.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 1, 'The two-speed brain', 'An impulse buy is a decision made by the fast, emotional part of your brain — before the slow, reasoning part has caught up. The gap between "I want that" and "I''ve bought that" can be under two seconds online. By the time your reasoning brain arrives, the purchase is often already done.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 2, 'Dopamine''s dirty trick', 'When you see something you want, your brain releases dopamine — a chemical tied to anticipation. Here''s the catch: the hit comes from wanting and buying. Not from owning. Which is exactly why the excitement fades within hours of getting the thing — and why buyer''s remorse is so common.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 3, 'Shops are engineered', 'None of this is accidental: Sweets at the till — you''re standing still, wallet already out. Essentials at the back — so you walk past everything else. Big trolleys — a normal shop looks sparse, so you add more. Slow music — you walk slower, browse longer. Every one of these has been tested. You''re walking through a designed environment, similar to a casino, built to work on your subconscious.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 4, 'Apps removed the pause', 'Physical shops at least make you queue. Apps deleted that: Card details already saved. "Buy now" is the biggest button on screen. Countdown timers — manufactured urgency. "3 people are viewing this" — manufactured competition. Pay-later options that make £60 feel like £15. Every feature exists to remove the moment where you might change your mind.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 5, 'Put the friction back', 'The fix is boringly simple: build in a delay. Basket it. Leave it 24 hours (small) or a week (big). Most of the time you won''t come back — which tells you the want was the moment, not the item. Two more that work: don''t save your card details, and unsubscribe from marketing emails. A lot of impulse buying starts with a notification you never asked for.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 1, 'Three lenses', 'You''ve now got three: Emotional association — the ad sells a feeling. Social pressure — "everyone has one". Engineered impulse — the pause has been removed.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 2, 'They almost never come alone', 'Watch a single 15-second social media ad: An aspirational creator uses it → association. "Selling out everywhere" → belonging + scarcity. 20% off, timer running → impulse. Three techniques, fifteen seconds, one clip. That''s normal, not unusual.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 3, 'What you''re about to do', 'Real scenarios. Name the technique — or techniques — doing the work. There''s no trick here: if you can spot them, they lose most of their power.');

insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 1, 1, 'mcq', 'An advert for a phone spends 25 seconds showing friends laughing at a festival, and 3 seconds showing the phone. Why is it built this way?', '["The phone''s features are too technical to explain quickly","Because the feeling is the product — you''re meant to link the phone to it","Adverts are legally limited in how long they can show a product","Festival footage is cheaper to film than product footage"]'::jsonb, '1', null, null, 'Features rarely create wanting. Feelings do. The advert borrows the feeling of the festival and attaches it to the phone — that''s emotional association, and it''s the most common technique in advertising.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 1, 2, 'text', 'What''s the name for the technique where an advert links a good feeling to a product, even though the product didn''t create that feeling?', '[]'::jsonb, 'emotional association', '["emotional association","association"]'::jsonb, null, 'Emotional association. Once you can name it, you start seeing it in almost every advert you watch.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 1, 3, 'multi', 'Which of these are advertising techniques covered in this lesson?', '["Aspiration — showing someone you''d like to be","Belonging — implying people like you already have it","Scarcity — \"limited edition\", \"ends tonight\"","Repetition — showing you the brand again and again","Comparison — showing a rival product side by side"]'::jsonb, '[0,1,2,3]', null, null, 'A, B, C and D. Comparison adverts do exist, but they work differently — they''re arguing about the product itself. The four listed all work on you rather than on the product.'),
  ('a9ccf186-f2a5-4702-a6f6-428d14ed09a0', 1, 4, 'mcq', 'Why does repetition work, even when you learn nothing new about the product?', '["Repeated adverts contain hidden messages","Seeing something often makes it feel familiar, and familiarity feels like trustworthiness","You eventually forget you disliked it","Brands that advertise more are usually higher quality"]'::jsonb, '1', null, null, 'Familiarity gets mistaken for quality. Your brain treats "I''ve seen this a lot" as "this must be fine" — a decent shortcut in most of life, an exploitable one in a shop. D is the misconception this question is checking: advertising budget says nothing about product quality.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 1, 1, 'num', 'In a class of 30, six people own a certain item. What percentage of the class owns it?', '[]'::jsonb, '20', null, null, '20% — one in five. It feels like far more because those six mention it constantly and the other 24 never announce what they don''t own. The sample you''re hearing from is skewed.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 1, 2, 'mcq', 'You spend £20 on a trend, using money you''d been saving toward something else. What did it actually cost you?', '["£20","£20, plus whatever you gave up by not saving it","Nothing — it was your money to spend","£20, minus whatever you''d already saved"]'::jsonb, '1', null, null, 'The price tag is only half the bill. The other half — what you gave up — is the opportunity cost, and it''s the part almost everyone forgets. It might still have been worth it; you just want to be counting both sides.'),
  ('ebd28e57-840f-4848-a744-620b9bdfe499', 1, 3, 'mcq', 'You run the invisibility test on something you want and honestly answer "not really — I''d only want it if people could see it." What''s the most useful conclusion?', '["You shouldn''t buy things you can''t justify","There''s something shallow about wanting to be seen","What you want is the social feeling, not the object — and that''s often available more cheaply","You should wait until the trend passes and buy it then"]'::jsonb, '2', null, null, 'Wanting to belong is normal, not a flaw — that''s not what the test is checking. It''s separating what you actually want from the object you''d have bought to get it. Once you know it''s the feeling, you can look for cheaper routes to it.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 1, 1, 'mcq', 'Why does the excitement of an impulse buy usually fade within hours?', '["You realise you paid too much","The dopamine hit comes from wanting and buying, not from owning","Most impulse buys are low quality","You get used to anything eventually"]'::jsonb, '1', null, null, 'Your brain rewards the chase, not the catch. By the time you own the thing, the chemical that made you want it has already done its job. D is partly true of everything, but it doesn''t explain why impulse buys fade so much faster than planned purchases.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 1, 2, 'mcq', 'A supermarket puts milk and bread at the very back of the store. Why?', '["They need to be near the refrigeration units","So you walk past everything else to reach them","To reduce queuing at the entrance","Because heavy items should go at the bottom of the trolley"]'::jsonb, '1', null, null, 'Store layout is a sales tool. Essentials go as far from the door as possible so your route is longer, you see more, and you buy more. A sounds sensible and is the common assumption — but chilled sections get built wherever the layout needs them.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 1, 3, 'multi', 'Which of these are deliberate design choices intended to increase spending?', '["Sweets positioned at the till","Slow-tempo music played in-store","Trolleys that are larger than most people need","Clear signage showing where each aisle is","\"3 people are viewing this item\" on a shopping app"]'::jsonb, '[0,1,2,4]', null, null, 'A, B, C and E. Clear signage helps you leave faster, which is why it''s the odd one out — it''s genuinely for you. Slow music is the one people rarely believe: slower tempo, slower walking, longer browsing.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 1, 4, 'mcq', 'You''re about to buy something online and a timer appears: "Offer ends in 4:59." What is it designed to do?', '["Reward customers who decide quickly","Show that the item is genuinely popular","Close the gap before your reasoning brain catches up","Comply with advertising rules about limited offers"]'::jsonb, '2', null, null, 'Artificial urgency exists to stop you thinking. Most of these timers reset when you reload the page — and even if the deal genuinely vanished, missing a discount costs far less than buying something you didn''t want.'),
  ('82f064a9-2163-4b74-bd17-734cb0e4e06a', 1, 5, 'mcq', 'Which of these is most likely to actually reduce impulse buying?', '["Setting a monthly spending limit","Leaving items in your basket for 24 hours before deciding","Only shopping when you have money spare","Comparing prices across several websites"]'::jsonb, '1', null, null, 'Delay works because it removes the thing impulse depends on — speed. The others are reasonable habits, but a limit doesn''t stop you spending it impulsively, and price-comparing an item you didn''t want just gets you a cheaper mistake.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 1, 1, 'multi', 'A gamer posts: "Been using this headset all week — everyone in my lobby has one now. Code SAVE20, ends Sunday." Which techniques are in play?', '["Aspiration — a creator you follow is using it","Belonging — \"everyone in my lobby has one\"","Scarcity/urgency — a code that expires","Repetition — you''ve seen the brand many times before"]'::jsonb, '[0,1,2]', null, null, 'A, B and C, stacked into one sentence. Repetition isn''t shown here — that''s about seeing a brand repeatedly over time, not within a single post. And the headset may still be genuinely good; both things can be true at once.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 1, 2, 'mcq', 'You see a friend''s new trainers. Yesterday you were happy with yours; today you''re not. What''s most likely happening?', '["Your trainers have worn out and you''d not noticed","The want was triggered socially, by seeing rather than needing","An advert you saw earlier is only now taking effect","Your taste has genuinely changed"]'::jsonb, '1', null, null, 'A want that appears the moment you see someone else''s version is almost always social. Worth running the invisibility test before you spend anything.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 1, 3, 'mcq', 'You''re queuing to pay, holding a £2 chocolate bar you didn''t come in for. Which describes it best?', '["A small, harmless purchase","An engineered impulse — the till display did exactly its job","Peer pressure","A genuine need, since you were hungry"]'::jsonb, '1', null, null, '£2 isn''t a disaster, and noticing is the whole point rather than guilt. But that display is there deliberately: you''re standing still, your wallet is out, the price is low, and there''s nothing to do but look.'),
  ('a1d391ea-c943-428b-87ab-98ad5e228acd', 1, 4, 'mcq', 'An advert shows a well-known athlete training in a particular brand, with the caption "Only 500 pairs made." Which two techniques are combined?', '["Repetition and belonging","Aspiration and scarcity","Belonging and impulse","Aspiration and repetition"]'::jsonb, '1', null, null, 'Aspiration (someone you''d like to be) plus scarcity (limited run). Neither says anything about whether the trainers are any good — which is the point of learning to name them.');

-- Public read access for curriculum content -- these tables hold no
-- student data, so it's safe to open read-only ahead of the auth/RLS
-- policy work still to come for the student-specific tables.
create policy "Public read access" on topics for select using (true);
create policy "Public read access" on subtopics for select using (true);
create policy "Public read access" on slides for select using (true);
create policy "Public read access" on questions for select using (true);
