-- Real Tier 2 content for Topic II.V — Scams & Financial Safety.
-- Same pattern as Tier 1: fixed UUIDs for topic/subtopic rows (safe to
-- re-run), slides/questions are a single-shot content load (no on-conflict
-- guard -- do not paste this file twice).

insert into topics (id, tier, "order", title, video_url)
values ('de3ffa2f-27e2-4d25-87fc-09b73a3c7937', 2, 5, 'Scams & Financial Safety', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 'de3ffa2f-27e2-4d25-87fc-09b73a3c7937', 'Common Scams Targeting Teens', 1),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 'de3ffa2f-27e2-4d25-87fc-09b73a3c7937', 'Phishing and Fake Messages', 2),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 'de3ffa2f-27e2-4d25-87fc-09b73a3c7937', 'Marketplace and Trading Scams', 3),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 'de3ffa2f-27e2-4d25-87fc-09b73a3c7937', 'What To Do If You Think You''ve Been Scammed', 4)
on conflict (id) do nothing;

insert into slides (subtopic_id, "order", heading, body)
values
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 1, 'Scams target situations, not stupidity', 'The most common belief about scams is that they happen to people who weren''t paying attention. That belief is itself a vulnerability, because it stops you checking. Scams work on urgency, excitement, and trust — states everyone experiences, regardless of how sharp they are.'),
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 2, 'The pattern behind almost all of them', 'Nearly every scam contains three ingredients: an offer that''s better than it should be — free, exclusive, way under market price. Pressure to act fast — expiring, limited, "only a few left". A step that''s hard to reverse — a payment, a code, a login, a transfer. That third one is the actual goal. Everything before it exists to get you there quickly.'),
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 3, 'Fake giveaways and prize scams', '"You''ve won" — but first there''s a small fee, or a form, or a login. The tell is simple: a genuine prize never requires payment to release it. Not a delivery charge, not a processing fee, not a verification payment. If money has to move toward them before anything moves toward you, it isn''t a prize.'),
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 4, 'Impersonation of people you trust', 'A message from a friend''s account asking for a favour, a code, or money. Accounts get compromised, and the scammer inherits the trust attached to that name. The defence isn''t suspicion of your friends — it''s a habit: verify through a different channel. Call them, message them somewhere else, ask something only they''d know. Thirty seconds of checking defeats almost every version of this.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 1, 'What phishing is', 'A message pretending to be from someone legitimate — a bank, a service, a delivery company, a school — designed to get you to click, log in, or hand over information. The name comes from fishing: cast widely, wait for anyone to bite.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 2, 'Why "it looked real" isn''t reassuring', 'Copying a logo, an email layout, and a tone of voice is trivial. Convincing appearance is the baseline, not evidence. Which is why judging a message by how professional it looks is the wrong test entirely. Real organisations and scammers can produce identical-looking messages.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 3, 'What actually distinguishes them', 'Not appearance — behaviour: urgency — act now, account suspended, final warning. A link that wants you to log in — the payload, almost always. Requests for details a real organisation already has — your bank knows your account number. Anything asking for a PIN, password, or one-time code — no legitimate organisation ever asks for these, ever. That last one is close to an absolute rule, and it''s worth holding onto as one.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 4, 'The habit that beats all of it', 'Never act through the message. Go to the service yourself — type the address, open the app you already have — and check there. If it''s real, you''ll see it. If it isn''t, you''ve lost eight seconds. This works even against messages you can''t tell apart from real ones, which is exactly why it''s the habit worth having rather than trying to get better at spotting fakes.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 1, 'Why these are especially common for teens', 'Game items, accounts, secondhand goods, resale apps — spaces where value moves between strangers, often outside any formal protection, frequently with no proper record of the deal. That combination is where scams concentrate.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 2, 'The pattern: who goes first', 'Almost every marketplace scam reduces to one question: who hands over their side first? The scam is engineered so you go first. You send the payment and the item never arrives; you send the item and the payment never comes; you hand over an account and it''s simply taken. Any pressure to go first, or to skip whatever protection the platform provides, is the signal.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 3, 'Off-platform is the red flag', '"Let''s do this on another app." "Pay directly, it''s quicker." "Send it as a gift so there''s no fee." Every one of these moves the deal outside whatever protection or record existed. That''s the entire reason it''s being suggested. Fee avoidance is the stated reason. Removing your ability to dispute it is the actual effect.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 4, 'Practical defences', 'Keep transactions on the platform, using its normal payment route. Don''t send money by methods designed to be irreversible. Screenshot the conversation and the listing. And be sceptical of prices well below what something normally goes for — that''s the anchor doing its job, and it''s the most reliable bait in the entire category.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 1, 'Speed matters more than certainty', 'Don''t wait until you''re sure. Acting on a suspicion costs you an awkward conversation. Waiting for proof costs you the window in which anything can be reversed.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 2, 'The immediate steps', 'Stop — send nothing more, no matter what the follow-up messages say. Tell a trusted adult — a parent, a teacher, someone at home. This is the step people skip out of embarrassment, and it''s the one that matters most. Contact the bank if money moved — call the number on the back of the card, or dial 159, which connects you straight to your bank''s fraud team. Some transactions can be stopped or challenged, but the window is short. Change passwords if any account or login was involved, starting with email. Report it — in the UK that''s Report Fraud, reportfraud.police.uk or 0300 123 2040. It replaced Action Fraud in December 2025. In Scotland, call Police Scotland on 101.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 3, 'Being scammed isn''t a character flaw', 'This matters, so it''s stated plainly: scams work on people of every age and every level of intelligence, including people who work in security. Shame is what scammers rely on afterwards. It''s why so much goes unreported, which is exactly what allows the same scam to keep working on the next person.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 4, 'After the immediate steps', 'Watch for follow-up scams. Being scammed once frequently leads to being targeted again — sometimes by someone posing as help, offering to recover what you lost, for a fee. Recovery scams are a real and well-documented category. Treat any unsolicited offer of help with the same caution as the original.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 5, 'What you''ve built this tier', 'You now know how to see your whole financial picture rather than half of it, how prices are engineered to steer you, why small recurring costs are the ones that escape notice, what BNPL actually is beneath the framing, and how to recognise and respond to the scams most likely to reach you. That''s Application. Two paths are still open. Mathematics takes the numbers underneath all of this — percentages, interest, compounding, inflation, risk — and shows you how they actually work. Mastery goes further still: the real formulas, value across time, behavioural finance, crypto, and a budgeting tool you build and code yourself in Python. Take whichever you actually want.');

insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 2, 1, 'mcq', 'Why is "scams only work on people who aren''t paying attention" a dangerous belief?', '["It''s true, but only for simple scams","It stops you checking, because you assume you''d notice","It makes people overly suspicious of everything","It discourages reporting"]'::jsonb, '1', null, null, 'The belief is itself the vulnerability. Scams work on urgency, excitement and trust — states everyone experiences regardless of how sharp they are. D is a real problem too, but it comes later, after someone''s been caught.'),
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 2, 2, 'multi', 'Which ingredients appear in nearly every scam?', '["An offer better than it should be","Pressure to act quickly","A step that''s hard to reverse","Poor spelling and obvious mistakes"]'::jsonb, '[0,1,2]', null, null, 'A, B and C are the structure. D is the one people are taught to look for and it''s increasingly unreliable — plenty of scams are well written, and treating good spelling as reassurance is exactly backwards.'),
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 2, 3, 'mcq', 'A message says you''ve won a prize, but there''s a small delivery fee to release it. What''s the tell?', '["The prize is described vaguely","A genuine prize never requires payment to release it","The fee is small relative to the prize","You don''t remember entering"]'::jsonb, '1', null, null, 'Not a delivery charge, not a processing fee, not a verification payment. If money has to move toward them before anything moves toward you, it isn''t a prize. A and D are also suspicious, but B is the rule that always holds.'),
  ('c9110f31-23d6-4b0f-817f-d798599a04d6', 2, 4, 'mcq', 'A friend messages asking you to send them a code that just arrived on your phone. What should you do?', '["Send it — you recognise the account","Verify through a different channel before doing anything","Reply asking why they need it","Send it, but ask them to explain afterwards"]'::jsonb, '1', null, null, 'Accounts get compromised, and a scammer inherits whatever trust that name carries. Call them, message them somewhere else, ask something only they''d know. C keeps the conversation with whoever is actually holding that account — which may not be your friend.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 2, 1, 'text', 'What''s the term for a message pretending to be from a legitimate organisation, designed to get you to click, log in, or hand over information?', '[]'::jsonb, 'phishing', '["phishing","phish"]'::jsonb, null, 'Phishing — from fishing: cast widely, wait for anyone to bite.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 2, 2, 'mcq', 'Why isn''t "it looked completely genuine" a good reason to trust a message?', '["Genuine organisations often send poorly designed messages","Copying a logo, layout and tone is trivial","Appearance varies between devices","Real messages usually contain more detail"]'::jsonb, '1', null, null, 'Convincing appearance is the baseline, not evidence. Real organisations and scammers can produce visually identical messages — which is why judging by how professional something looks is the wrong test entirely.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 2, 3, 'multi', 'Which of these are genuine warning signs in a message?', '["Urgency — act now, account suspended, final warning","A link that asks you to log in","A request for a PIN, password or one-time code","A request for details the organisation would already have","The message arriving outside office hours"]'::jsonb, '[0,1,2,3]', null, null, 'A, B, C and D are all behavioural signals. E isn''t — automated messages arrive at all hours legitimately. C is closest to an absolute rule: no legitimate organisation ever asks for these.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 2, 4, 'mcq', 'You get a message from your bank saying your account will be suspended unless you confirm your details. What''s the safest response?', '["Check the sender''s address carefully before clicking","Open your banking app yourself and check there","Reply asking them to confirm who they are","Click the link but don''t enter your password"]'::jsonb, '1', null, null, 'Going to the service yourself works even against messages you can''t tell apart from real ones — which is why it beats trying to get better at spotting fakes. If it''s real, you''ll see it there. If not, you''ve lost eight seconds. A is reasonable but sender addresses can be spoofed.'),
  ('d70f05c4-1cec-476b-877e-e4ae771dadb5', 2, 5, 'mcq', 'A bank will sometimes ask for your PIN or a one-time code to verify your identity over the phone.', '["True","False"]'::jsonb, '1', null, null, 'Never — by phone, email or message. This is close to an absolute rule and worth holding onto as one. Anyone asking is attempting fraud, no matter how convincing the rest of the call sounds.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 2, 1, 'mcq', 'What single question does almost every marketplace scam come down to?', '["Is the price too good to be true?","Who hands over their side first?","Does the seller have reviews?","Is the item genuine?"]'::jsonb, '1', null, null, 'The scam is engineered so you go first — you send payment and nothing arrives, or you send the item and nothing comes back. Everything else is set-up for that moment.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 2, 2, 'mcq', 'Someone suggests completing a deal on a different app to avoid the platform''s fees. What''s actually happening?', '["They''re being helpful about costs","They''re removing your ability to dispute it","They''re avoiding tax","They prefer that app''s interface"]'::jsonb, '1', null, null, 'Fee avoidance is the stated reason; removing the record and the protection is the effect. That''s the entire reason it''s being suggested — and the request itself is the signal, regardless of how reasonable it sounds.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 2, 3, 'multi', 'Which of these reduce your risk in a marketplace trade?', '["Keeping the transaction on the platform","Screenshotting the listing and the conversation","Sending money as a gift to avoid fees","Using the platform''s normal payment route"]'::jsonb, '[0,1,3]', null, null, 'A, B and D all preserve either protection or evidence. C removes both — payment methods designed to be irreversible are exactly what a scammer wants you to use, which is why the suggestion so often comes from them.'),
  ('e76f4a7b-256a-4e4a-bc31-151161ccd1f7', 2, 4, 'mcq', 'An item is listed well below what it normally sells for. What''s the most accurate reading?', '["A bargain worth acting on quickly","A price set low deliberately to trigger fast action","The seller doesn''t know its value","The item is probably faulty"]'::jsonb, '1', null, null, 'The unusually low price is the anchor doing its job — it creates urgency and makes checking feel like it might cost you the deal. That''s the most reliable bait in the whole category. Genuine bargains exist, which is exactly what makes it work.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 2, 1, 'mcq', 'You suspect you''ve been scammed but aren''t certain. What should you do?', '["Wait until you''re sure before acting","Act now — the window for reversing things is short","Contact the person to check","Monitor your account for a few days"]'::jsonb, '1', null, null, 'Acting on a suspicion costs an awkward conversation. Waiting for proof costs the window in which anything can be reversed. C is actively risky — it tells whoever it is that you''ve noticed.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 2, 2, 'num', 'What number connects you directly to your bank''s fraud team in the UK?', '[]'::jsonb, '159', null, null, '159 works with most major UK banks and connects you straight through — genuinely worth remembering before you need it. The number on the back of your card works too.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 2, 3, 'text', 'What is the UK''s national service for reporting fraud and cyber crime, which replaced Action Fraud in December 2025?', '[]'::jsonb, 'report fraud', '["report fraud","reportfraud","report fraud police","reportfraud.police.uk"]'::jsonb, null, 'Report Fraud — reportfraud.police.uk or 0300 123 2040. It covers England, Wales and Northern Ireland; in Scotland you report to Police Scotland on 101.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 2, 4, 'multi', 'Which of these are appropriate immediate steps after being scammed?', '["Stop — send nothing further","Tell a trusted adult","Contact the bank if money moved","Change passwords if a login was involved","Reply to establish what happened"]'::jsonb, '[0,1,2,3]', null, null, 'A through D are all right, and B is the one people skip out of embarrassment despite it mattering most. E keeps the conversation going with someone who has every reason to keep manipulating you.'),
  ('61112cd3-7da4-4e09-8615-2988e55806b1', 2, 5, 'mcq', 'Weeks after being scammed, someone contacts you offering to recover your money for a fee. What is this most likely to be?', '["A legitimate recovery service","A follow-up scam targeting you again","Your bank''s fraud department","A government compensation scheme"]'::jsonb, '1', null, null, 'Recovery scams are a real and well-documented category — being scammed once frequently leads to being targeted again, sometimes by someone posing as help. Treat any unsolicited offer of assistance with the same caution as the original approach.');
