-- Real Tier 2 content for Topic II.II — How Pricing Tricks You.
-- Same pattern as Tier 1: fixed UUIDs for topic/subtopic rows (safe to
-- re-run), slides/questions are a single-shot content load (no on-conflict
-- guard -- do not paste this file twice).

insert into topics (id, tier, "order", title, video_url)
values ('12f4555d-28bf-4a83-a76d-397992298da4', 2, 2, 'How Pricing Tricks You', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', '12f4555d-28bf-4a83-a76d-397992298da4', 'Fake Discounts', 1),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', '12f4555d-28bf-4a83-a76d-397992298da4', 'Unit Pricing', 2),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', '12f4555d-28bf-4a83-a76d-397992298da4', 'Psychological Pricing', 3),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', '12f4555d-28bf-4a83-a76d-397992298da4', 'Practice: Spot the Trick', 4)
on conflict (id) do nothing;

insert into slides (subtopic_id, "order", heading, body)
values
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 1, '"Was £50, now £30" is a claim, not a fact', 'Two numbers do very different jobs on that label. £30 is what you''ll pay. £50 is there to tell you how to feel about £30. And the second number is far easier to manipulate than the first.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 2, 'Anchoring', 'There''s a name for why this works: anchoring. Whatever number your brain sees first becomes the reference point everything else gets measured against. Shown £30 alone, you''d judge it on whether £30 is worth it. Shown "was £50", you judge it on the £20 you''ve apparently saved — a completely different question, and one where the answer is always flattering.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 3, 'There are actually rules about this', 'Misleading someone about a price is against the law in the UK, and the rules got sharper recently. Under the Digital Markets, Competition and Consumers Act 2024, misleading reference pricing — a "was" price that was never really the price — is prohibited, alongside things like hidden fees added late in checkout and fake countdown timers. The regulator can fine a company up to 10% of its worldwide turnover, and has already opened investigations into businesses over exactly these practices. So the rules exist and have teeth. But enforcement happens after the fact, on a company scale — it doesn''t help you standing in front of a shelf. That part is still on you.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 4, 'The check that actually works', 'Ignore both numbers on the label and ask one question: is £30 a good price for this thing? Not "is £30 better than £50" — that''s the question you''re being handed. Search what it costs elsewhere. Price-history sites exist for exactly this. Ten seconds of checking beats any amount of staring at a crossed-out number.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 5, 'Sales aren''t fake — the framing might be', 'Genuine discounts absolutely exist. Shops clear old stock, seasons end, real reductions happen constantly. The skill isn''t cynicism, it''s separating two questions: is this cheaper than it was? and is this a good price? Only the second one costs you money if you get it wrong.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 1, 'Bigger looks cheaper, and usually is', 'Buying in bulk normally does cost less per unit, which is exactly why the assumption is so easy to exploit. It''s true often enough that you stop checking.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 2, 'Do the division', 'The unit price is what you pay per gram, per millilitre, per item — rather than per package. 500ml for £1.20 works out to £1.20 ÷ 5 = £0.24 per 100ml. 750ml for £1.95 works out to £1.95 ÷ 7.5 = £0.26 per 100ml. The bigger bottle costs more per 100ml. It looks like the value option because it''s bigger and the total price is higher, which your brain reads as "more for your money."'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 3, 'Shops have to show it, and it just got stricter', 'UK shops are legally required to display a unit price on many products — usually small, under the main price, in a format like "£2.40 per litre". Rules that took effect in April 2026 widened the range of products that need one, standardised the units used so packs can actually be compared, and required the price to be legible rather than technically present. All of which only matters if you look at it. The rule makes comparison possible; it can''t make you do it.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 4, 'Even a right answer can be wrong', 'Cheaper per unit only helps if you''ll use it all. A larger pack at a genuinely better unit price is worse value if a third of it goes to waste. The correct comparison isn''t per gram — it''s per gram you''ll actually use. That''s the part unit pricing can''t tell you, and it''s why judgement still matters after the maths is done.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 1, '£9.99 and £10 are one penny apart', 'And they don''t feel it.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 2, 'The left-digit effect', 'You read left to right, and your brain forms an impression before it finishes. £9.99 registers as "nine-something." £10.00 registers as "ten." The gap you perceive isn''t one penny — it''s a whole pound, because the first digit changed. This is called the left-digit effect, and it''s why prices ending in 99 are everywhere. It isn''t tradition or rounding. It''s tested, and it works.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 3, 'The other signals a price sends', 'Prices ending in 99 also carry a message: this is a bargain, a deal, good value. Which is why premium brands frequently do the opposite — £40 rather than £39.99. A round number signals confidence and quality; a 99 ending signals discount. Neither tells you anything about the actual product.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 4, 'Round it up before you judge it', 'The fix takes a second: mentally round to the nearest pound before deciding. £9.99 becomes "ten pounds." £24.99 becomes "twenty-five pounds." Then ask whether that number is worth it. You''re not being tricked out of a penny. You''re being nudged into judging the price by its first digit — and rounding removes the nudge entirely.'),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', 1, 'Three tools now', 'Anchoring — the crossed-out price is framing, not information. Unit pricing — divide before you assume bigger is better. Left-digit effect — round up before you judge.'),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', 2, 'They stack', 'A real shelf can carry all three at once: a "was £24.99, now £19.99" label on a large pack whose unit price is worse than the small one beside it. Three techniques, one label. Spotting them isn''t about catching anyone out — it''s about paying the price you decided on rather than the one you were steered toward.');

insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 2, 1, 'text', 'What''s the term for the effect where the first number you see becomes the reference point you judge everything else against?', '[]'::jsonb, 'anchoring', '["anchoring","anchor","anchoring effect","anchor effect"]'::jsonb, null, 'Anchoring. It''s why "was £50, now £30" works — the £50 sets the frame, and you end up judging the £20 you apparently saved rather than whether £30 is a good price.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 2, 2, 'mcq', 'A label reads "Was £80, now £48." What''s the more useful question to ask?', '["How long the offer lasts","Whether £48 is a good price for this item","Whether the saving is worth £32","Why the price dropped so much"]'::jsonb, '1', null, null, '"Is £48 good?" is answerable by checking elsewhere. "Is the saving worth it?" is the question the label handed you, and it flatters the answer every time. C is the trap: it accepts the £80 as real before doing any thinking.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 2, 3, 'mcq', 'In the UK, a shop can legally advertise "was £50" even if the item never sold at £50.', '["True","False"]'::jsonb, '1', null, null, 'Misleading reference pricing is prohibited under UK law, and the regulator can fine a company up to 10% of its worldwide turnover — with enforcement cases already opened. But rules operate after the fact and at company scale. They don''t help you standing in front of a shelf, which is why the check still matters.'),
  ('9e728e1f-6a4a-4393-9557-af3c0aa849ae', 2, 4, 'mcq', 'Which is the most accurate view of discounts?', '["Most \"sales\" are manipulated and should be ignored","A discount is only genuine if the item is cheap","Real discounts are common — the question is whether the current price is good","Discounts are reliable if the shop is well known"]'::jsonb, '2', null, null, 'Shops clear stock and end seasons constantly, so genuine reductions are everywhere. The skill isn''t cynicism, it''s separating "is this cheaper than it was?" from "is this a good price?" Only the second one costs you money if you get it wrong.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 2, 1, 'text', 'What''s the term for the cost of a product per gram, per litre or per item, rather than per package?', '[]'::jsonb, 'unit price', '["unit price","unit pricing","price per unit"]'::jsonb, null, 'The unit price. It''s the number that makes two differently-sized packs actually comparable, and UK shops are required to display it on many products.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 2, 2, 'num', 'A 400ml bottle costs £1.60. What is the price in pence per 100ml?', '[]'::jsonb, '40', null, null, '400ml is 4 lots of 100ml, so £1.60 ÷ 4 = £0.40, which is 40p per 100ml. Doing this division is the entire skill — it turns two prices you can''t compare into two you can.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 2, 3, 'mcq', 'A 250g pack costs £2.00. A 600g pack costs £5.10. Which is better value per gram?', '["The 250g pack","The 600g pack","They''re identical","There isn''t enough information"]'::jsonb, '0', null, null, '£2.00 ÷ 250 = 0.8p per gram. £5.10 ÷ 600 = 0.85p per gram. The smaller pack is cheaper per gram, despite looking like the worse deal — bigger packs usually are better value, which is exactly why the assumption is worth checking rather than trusting.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 2, 4, 'mcq', 'A large pack has a genuinely better unit price than the small one, but you''d only use about half of it before it went off. Which is better value?', '["The large pack — the unit price is lower","The small pack, if you''d use all of it","Whichever has the lower total price","They''re equivalent once waste is included"]'::jsonb, '1', null, null, 'The right comparison isn''t cost per gram — it''s cost per gram you''ll actually use. Throwing half of a cheaper pack away can easily make it the more expensive choice. That''s the part the shelf label can''t tell you.'),
  ('d379afb7-68d8-44ab-910c-e9a02f2e4fae', 2, 5, 'mcq', 'UK shops are required to display unit prices on many products, and the rules were expanded in 2026 to cover more items and standardise the units used.', '["True","False"]'::jsonb, '0', null, null, 'Wider product scope, standardised units so packs can actually be compared, and a legibility requirement so the price is readable rather than just technically present. The rule makes comparison possible — it can''t make you look.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 2, 1, 'text', 'What''s the name for the effect where £9.99 feels much cheaper than £10.00 because your brain reads the first digit first?', '[]'::jsonb, 'left-digit effect', '["left-digit effect","left digit effect","left-digit bias","left digit bias"]'::jsonb, null, 'The left-digit effect. £9.99 registers as "nine-something", £10 registers as "ten" — so the gap you perceive is nearly a pound rather than a penny.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 2, 2, 'mcq', 'Why do some premium brands deliberately price at £40 rather than £39.99?', '["Round numbers are easier to process","A 99 ending signals discount, which conflicts with a premium image","It''s a legal requirement above a certain price","It reduces the cost of handling change"]'::jsonb, '1', null, null, 'Price endings carry a message beyond the number. 99 says bargain; a round figure says confidence and quality. Neither tells you anything about the actual product — which is the useful thing to notice.'),
  ('8da018eb-77b1-4a63-8014-38bde1c5cecb', 2, 3, 'mcq', 'What''s the practical defence against the left-digit effect?', '["Only buy items priced in round numbers","Round the price up mentally before deciding","Ignore prices ending in 99","Compare against the item''s original price"]'::jsonb, '1', null, null, 'Round £24.99 to "twenty-five pounds," then ask if that is worth it. You''re not being tricked out of a penny — you''re being nudged into judging by the first digit, and rounding removes the nudge entirely.'),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', 2, 1, 'mcq', 'A shelf label reads "Was £24.99, now £19.99" on a 900g pack. The 300g pack beside it costs £6.30. Which pricing techniques are in play?', '["Anchoring only","Anchoring, a 99-ending price, and a large pack with a worse unit price","Unit pricing only","None — this is a straightforward discount"]'::jsonb, '1', null, null, '£19.99 ÷ 900 = 2.22p per gram; £6.30 ÷ 300 = 2.1p per gram, so the big pack is worse per gram. Add the crossed-out anchor and the 99 ending and there are three techniques on one label.'),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', 2, 2, 'num', 'A 900g pack costs £19.80. What is the price in pence per 100g?', '[]'::jsonb, '220', null, null, '900g is 9 lots of 100g, so £19.80 ÷ 9 = £2.20, which is 220p per 100g. Converting to a common unit is the only way to compare packs of different sizes honestly.'),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', 2, 3, 'mcq', 'Two items are both reduced. Item A: was £30, now £24. Item B: was £120, now £96. Which is the better deal?', '["Item B — the saving is much larger","Item A — the saving is a smaller commitment","Neither — the reduction tells you nothing about whether either price is good","They''re identical — both are 20% off"]'::jsonb, '2', null, null, 'Both are 20% off, so D is arithmetically true but answers the wrong question. The size of a reduction says nothing about whether £24 or £96 is a good price for that particular thing — only checking elsewhere does. A is the anchor doing its job perfectly.'),
  ('6446cf99-4d2f-4abf-9b6d-718950880b0a', 2, 4, 'multi', 'Which of these are pricing techniques rather than useful information?', '["A crossed-out higher price beside the current one","A price ending in 99","The unit price printed under the main price","A larger pack displayed as the \"value\" option without a unit comparison"]'::jsonb, '[0,1,3]', null, null, 'A, B and D all steer your judgement. C is the odd one out — the unit price is genuinely there to help you compare, which is why it''s required by law and why almost nobody reads it.');
