-- Real Tier 2 content for Topic II.IV — Buy Now, Pay Later.
-- Same pattern as Tier 1: fixed UUIDs for topic/subtopic rows (safe to
-- re-run), slides/questions are a single-shot content load (no on-conflict
-- guard -- do not paste this file twice).

insert into topics (id, tier, "order", title, video_url)
values ('4c5646c9-4155-4d60-b151-40d2a89c2a41', 2, 4, 'Buy Now, Pay Later', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', '4c5646c9-4155-4d60-b151-40d2a89c2a41', 'What BNPL Actually Is', 1),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', '4c5646c9-4155-4d60-b151-40d2a89c2a41', 'Why It Feels Free', 2),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', '4c5646c9-4155-4d60-b151-40d2a89c2a41', 'What Happens If You Can''t Pay', 3),
  ('b8380f7a-736b-424a-b564-99d093c70250', '4c5646c9-4155-4d60-b151-40d2a89c2a41', 'Practice: Spotting BNPL', 4)
on conflict (id) do nothing;

insert into slides (subtopic_id, "order", heading, body)
values
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 1, 'The mechanism, plainly', 'You get the item now. A company pays the shop on your behalf. You repay that company in instalments over the following weeks. Which means, stripped of the branding: you have borrowed money. The item is yours before the money is.'),
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 2, 'Why it looks different from borrowing', 'It''s offered at the checkout, alongside the payment methods, framed as a way to pay rather than a way to borrow. There''s usually no interest advertised, often no obvious application, and the language avoids words like loan or credit entirely. None of that changes what''s happening. It changes how it feels while it''s happening — which is precisely the design.'),
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 3, 'Why shops offer it', 'Because it works. Customers who use BNPL tend to complete purchases they''d otherwise abandon, and often spend more per order. The shop pays a fee to the BNPL company for that. That fee is worth paying because of what it does to sales — which tells you plainly who this feature was built for.'),
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 4, 'Where you''ll actually meet it', 'Not just clothing sites. It''s increasingly at checkouts across online shopping, in-app purchases, event tickets, and games. Sometimes it''s the pre-selected option, sitting above paying in full. That''s a design choice too.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 1, 'Splitting changes the number you judge', '£60 gets compared against what''s in your account. "3 payments of £20" gets compared against £20. Same total. Completely different comparison — and the second one clears far more easily.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 2, 'The future is where the cost goes', 'Two of those three payments belong to a version of you that doesn''t exist yet, and that person always seems better off than the current one. Present bias — the tendency to weigh right now far more heavily than later — is one of the most consistent findings in behavioural economics, and BNPL is built directly on top of it. The benefit arrives immediately; the cost is delivered to someone who feels hypothetical. Mastery goes deeper into behavioural finance.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 3, 'Stacking is the real risk', 'One BNPL purchase is manageable. That''s how it starts. The danger is that each individual decision feels small and separate, while the repayments arrive on top of each other. Three purchases across three weeks can mean three overlapping repayment schedules — and nothing at any single checkout showed you that combined picture.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 4, 'The test that cuts through it', 'Could I pay the full amount today? If yes, BNPL is just a scheduling choice — repay on time and it may genuinely cost you nothing. If no, then the split isn''t helping you afford it. It''s helping you buy something you can''t afford yet, and the difference between those two sentences is where people get into trouble.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 1, 'The rules changed in July 2026', 'Until very recently, most BNPL in the UK sat outside the rules that cover other kinds of borrowing. That ended on 15 July 2026, when it came under the Financial Conduct Authority — the same regulator that oversees banks and credit cards. You''re learning this in the first months of a new system, which is unusual and genuinely useful. It also means anything written about BNPL before mid-2026 describes a world that no longer applies.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 2, 'What the new rules actually give you', 'Four things worth knowing: affordability checks — providers now have to assess whether you can realistically repay, rather than just approving you. Clear information up front — including what happens if you miss a payment, before you agree rather than after. Support if you''re struggling — providers are required to help people in financial difficulty, not just charge them. Protection on the purchase — broadly the same protection you''d get paying by credit card, if something goes wrong with what you bought. That''s a meaningfully better deal than existed a year ago.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 3, 'What hasn''t changed', 'It''s still borrowing, and missed payments still cost you. Late fees still exist and still vary between providers. Missed payments can still be reported to credit reference agencies — the organisations that build the record lenders check later, which affects renting a place, phone contracts, and future borrowing. Better rules make the product safer. They don''t make it free, and they don''t repay it for you.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 4, 'What to do if you''re struggling', 'The single worst response is silence, because costs accumulate while nothing gets resolved. Contact the provider early — they''re now required to support customers in difficulty, so this is a rule in your favour rather than a favour you''re asking for. Tell a trusted adult. Money problems grow in private and shrink when someone else is looking at them with you. And free, independent debt advice exists in the UK — StepChange, National Debtline, Citizens Advice and MoneyHelper all offer it at no cost. You should never have to pay for basic debt advice.'),
  ('b8380f7a-736b-424a-b564-99d093c70250', 1, 'What to look for', 'The words vary — "pay in 3", "split your payment", "pay later", "instalments", "£20 today" — but the structure is always the same: you take the thing now and owe money afterwards.'),
  ('b8380f7a-736b-424a-b564-99d093c70250', 2, 'Where it hides', 'Beyond online shopping: in-game purchases, ticketing, food delivery, and app-based marketplaces. Sometimes it''s the default selected option. Sometimes the total price is displayed less prominently than the instalment. Both are choices someone made.'),
  ('b8380f7a-736b-424a-b564-99d093c70250', 3, 'What you''ll practise', 'Real checkout scenarios. Identify whether BNPL is being offered, what the actual total is, and whether the framing is showing you the full price or just the first slice of it.');

insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 2, 1, 'mcq', 'Stripped of its branding, what is Buy Now Pay Later?', '["A payment method, like a debit card","Borrowing — you have the item before the money","A discount for paying over time","A savings plan applied to a purchase"]'::jsonb, '1', null, null, 'A company pays the shop on your behalf and you repay them. That''s borrowing, regardless of what the checkout button calls it. A is how it''s presented, which is precisely the design being described.'),
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 2, 2, 'mcq', 'Why does BNPL feel different from other borrowing?', '["The amounts involved are smaller","It''s presented as a way to pay rather than a way to borrow","It doesn''t involve a company lending money","There''s no agreement to sign"]'::jsonb, '1', null, null, 'It appears at checkout alongside the payment methods, usually with no interest advertised and language that avoids "loan" or "credit" entirely. None of that changes the mechanism — it changes how it feels while it''s happening.'),
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 2, 3, 'mcq', 'Why do shops offer BNPL when it costs them a fee?', '["It''s required for online sales","Customers complete more purchases and often spend more per order","It reduces the shop''s payment processing costs","It shifts responsibility for refunds to the lender"]'::jsonb, '1', null, null, 'The fee is worth paying because of what it does to sales — which tells you plainly who the feature was designed to benefit. That''s not a reason to avoid it, just a useful thing to know about who''s on which side.'),
  ('dd8115f0-7ce5-4d50-8fd2-82daaf259efa', 2, 4, 'mcq', 'BNPL is only offered on clothing and fashion websites.', '["True","False"]'::jsonb, '1', null, null, 'It appears across online shopping, in-app purchases, event tickets, food delivery and games. Sometimes it''s the pre-selected option sitting above paying in full — which is itself a design choice.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 2, 1, 'num', 'An item is offered as "4 payments of £17.50". How many pounds does it actually cost in total?', '[]'::jsonb, '70', null, null, '4 × £17.50 = £70. Splitting changes what the number gets compared against — £17.50 against your balance clears far more easily than £70 does — but the total is identical.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 2, 2, 'text', 'What''s the term for the tendency to weigh what''s happening now much more heavily than what happens later?', '[]'::jsonb, 'present bias', '["present bias","present-bias","hyperbolic discounting"]'::jsonb, null, 'Present bias. BNPL is built directly on top of it — the benefit arrives immediately, and the cost is delivered to a future version of you who always seems better off than the current one.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 2, 3, 'mcq', 'Why is using BNPL for several purchases riskier than using it once?', '["Providers charge more for repeat customers","Each decision feels separate, but the repayments arrive on top of each other","Multiple agreements are harder to cancel","Interest accumulates across agreements"]'::jsonb, '1', null, null, 'Three purchases across three weeks can mean three overlapping repayment schedules — and nothing at any single checkout showed you the combined picture. Each decision looked small on its own, which is exactly how the stack builds.'),
  ('4b11628c-ff04-4a0f-a29a-6b9ed2e84caa', 2, 4, 'mcq', 'What''s the most useful question to ask before using BNPL?', '["Can I afford the first instalment?","Could I pay the full amount today?","Is the item worth the total price?","How long are the repayments spread over?"]'::jsonb, '1', null, null, 'If yes, BNPL is just a scheduling choice and may genuinely cost nothing. If no, the split isn''t helping you afford it — it''s helping you buy something you can''t afford yet. The difference between those two sentences is where people get into trouble.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 2, 1, 'mcq', 'What changed for Buy Now Pay Later in the UK on 15 July 2026?', '["It became illegal for under-18s","It came under Financial Conduct Authority regulation, like other borrowing","Providers were required to charge interest","Late fees were abolished"]'::jsonb, '1', null, null, 'Before that date most BNPL sat outside the rules covering other kinds of credit. It''s now overseen by the same regulator as banks and credit cards — which brings affordability checks, clearer information, and a duty to support customers in difficulty.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 2, 2, 'multi', 'Which protections do the UK''s BNPL rules now provide?', '["Providers must check you can realistically afford the repayments","Clear information up front, including what happens if you miss a payment","A guarantee that missed payments won''t affect your credit record","Providers must support customers in financial difficulty","Protection on the purchase broadly similar to paying by credit card"]'::jsonb, '[0,1,3,4]', null, null, 'A, B, D and E are all real protections under the new rules. C is the misconception worth catching — better regulation makes the product safer, but missed payments can still be reported to credit reference agencies.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 2, 3, 'mcq', 'Now that BNPL is regulated in the UK, missing a payment no longer has consequences.', '["True","False"]'::jsonb, '1', null, null, 'Late fees still exist and still vary between providers, and missed payments can still be reported to credit reference agencies — affecting renting a place, phone contracts and future borrowing. Better rules make it safer; they don''t make it free, and they don''t repay it for you.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 2, 4, 'mcq', 'Someone realises they can''t make an upcoming BNPL payment. What''s the best first move?', '["Wait and see whether the payment goes through","Contact the provider before the payment is due","Take out another BNPL agreement to cover it","Cancel the card the payments come from"]'::jsonb, '1', null, null, 'Providers are now required to support customers in difficulty — so this is a rule in your favour, not a favour you''re asking for. A is the most common response and the worst: costs accumulate while nothing gets resolved. C makes the stack bigger, and D stops the payment without stopping the debt.'),
  ('faebeaa4-770d-418f-99ea-cd5bda3e0e4e', 2, 5, 'mcq', 'Where can someone in the UK get debt advice, and what should it cost?', '["A financial adviser, for a small fee","Free, from charities and services like StepChange, National Debtline or Citizens Advice","Only from their bank, free of charge","From the BNPL provider, for a fee"]'::jsonb, '1', null, null, 'Free, independent debt advice exists and you should never have to pay for it. That''s worth knowing before you need it — paid "debt help" companies specifically target people who don''t know the free services exist.'),
  ('b8380f7a-736b-424a-b564-99d093c70250', 2, 1, 'multi', 'Which of these checkout options are Buy Now Pay Later in some form?', '["\"Pay in 3 — £15 today\"","\"Split your payment over 6 weeks\"","\"Save 10% by paying in full\"","\"4 interest-free instalments\""]'::jsonb, '[0,1,3]', null, null, 'A, B and D all mean you take the item now and owe money afterwards, whatever the wording. C is a discount for paying up front — the opposite arrangement.'),
  ('b8380f7a-736b-424a-b564-99d093c70250', 2, 2, 'num', 'A checkout shows "£24 today" for an item offered as 3 equal instalments. How many pounds is the full price?', '[]'::jsonb, '72', null, null, '3 × £24 = £72. When the instalment is displayed more prominently than the total, that''s the number you''re being invited to judge — so working the total out yourself is the whole defence.'),
  ('b8380f7a-736b-424a-b564-99d093c70250', 2, 3, 'mcq', 'On a checkout page, BNPL is pre-selected above "pay in full". What does that tell you?', '["It''s the cheaper option","Most customers choose it","Someone chose to make it the default","The shop requires it for this item"]'::jsonb, '2', null, null, 'Defaults are decisions, and people mostly go with whatever''s already selected. Placing BNPL above paying in full, pre-ticked, is a design choice made by someone with an interest in which one you pick.');
