-- Real Tier 1 content for Topics I.II through I.V (Topic I.I was loaded separately).
-- Same pattern as the first content migration: fixed UUIDs for topic/subtopic
-- rows (safe to re-run), slides/questions are a single-shot load.
--
-- Two content-mapping decisions, flagged for review:
-- 1. True/false questions are stored as question_type = 'mcq' with
--    options ["True","False"] -- there's no dedicated true_false UI component,
--    and a T/F question is just a 2-option MCQ, so this reuses the existing,
--    tested renderer rather than adding a new one for 6 questions.
-- 2. The one "put these in order" question (I.III.I) is stored as a 4-option
--    MCQ describing possible orderings, per instruction, since drag-to-reorder
--    wasn't worth building for a single question.

insert into topics (id, tier, "order", title, video_url)
values
  ('74756132-b771-4829-9543-b3dea39d7065', 1, 2, 'Where Money Really Comes From', null),
  ('8411e144-bebf-4a31-9173-f159988abf67', 1, 3, 'Making Money Decisions With What You Have', null),
  ('22f62d11-54ea-42f6-b31b-3f473393b716', 1, 4, 'How Banks and Money Actually Work', null),
  ('39fc0bdd-a692-49de-b7be-73f6928e44b6', 1, 5, 'Setting a Goal That Actually Matters to You', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', '74756132-b771-4829-9543-b3dea39d7065', 'Earning Through Work', 1),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', '74756132-b771-4829-9543-b3dea39d7065', 'Family Circumstances Differ', 2),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', '74756132-b771-4829-9543-b3dea39d7065', 'Other Ways Money Shows Up', 3),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', '74756132-b771-4829-9543-b3dea39d7065', 'Why Understanding This Helps You Plan Ahead', 4),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', '8411e144-bebf-4a31-9173-f159988abf67', 'Prioritising When Money Is Limited', 1),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', '8411e144-bebf-4a31-9173-f159988abf67', 'Small Amounts Still Count', 2),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', '8411e144-bebf-4a31-9173-f159988abf67', 'Needs vs Wants, Applied', 3),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', '8411e144-bebf-4a31-9173-f159988abf67', 'Practice: Deciding With a Fixed Amount', 4),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', '22f62d11-54ea-42f6-b31b-3f473393b716', 'What a Bank Account Actually Does', 1),
  ('bcd69b01-2151-42c8-8038-f38c08462713', '22f62d11-54ea-42f6-b31b-3f473393b716', 'Debit Cards Explained', 2),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', '22f62d11-54ea-42f6-b31b-3f473393b716', 'Why Banks Are Safer Than Cash', 3),
  ('35318b34-1b76-4329-9655-6b20e790b460', '22f62d11-54ea-42f6-b31b-3f473393b716', 'Debit vs Credit', 4),
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', '39fc0bdd-a692-49de-b7be-73f6928e44b6', 'Why Goals Work Better Than "Just Saving"', 1),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', '39fc0bdd-a692-49de-b7be-73f6928e44b6', 'Building a Realistic Goal', 2),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', '39fc0bdd-a692-49de-b7be-73f6928e44b6', 'Worked Examples', 3),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', '39fc0bdd-a692-49de-b7be-73f6928e44b6', 'Practice: Build Your Own Goal', 4)
on conflict (id) do nothing;

-- Topic I.II slides
insert into slides (subtopic_id, "order", heading, body)
values
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 1, 'Pay isn''t a difficulty score', 'Most people assume harder work means more pay. It doesn''t hold — some physically exhausting jobs pay less than jobs done sitting down. That''s not because the system is fair or unfair. It''s because pay isn''t measuring effort at all.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 2, 'What pay is actually measuring', 'Three things, roughly: how many people can do it — rare skill, higher pay. How many people want to do it — unpleasant jobs pay more to attract anyone. How much value it creates — for whoever''s paying. That''s it. Effort isn''t on the list.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 3, 'Why that matters now', 'If pay tracked effort, the strategy would be: work harder. Since it tracks scarcity and value, the strategy is to become someone who can do something most people can''t. That''s a much better use of being your age than picking up extra work and doing as many activities as possible.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 4, 'The rules that apply to you — and the gap most people don''t realise', 'Most countries set rules around when someone your age can legally work, and how many hours. Here''s the part that surprises people: below a certain age — usually somewhere around 15 or 16 — there is often no minimum wage protection at all. Once you''re old enough to legally work full-time, minimum wage rates usually apply, and they''re usually lower for younger workers than for adults, rising as you get older. The exact ages and rates are different in every country, and they change over time. The habit that matters isn''t memorising a number — it''s knowing to check your own country''s current rules before agreeing to any paid work, especially while you''re under the age where protections fully apply.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 5, 'The number you''re offered isn''t the number you keep', 'The number you''re offered isn''t always the number you receive. Gross pay is the headline figure. Net pay, or take-home pay, is what actually lands, after tax and any other deductions are taken out. Most people your age earn under whatever tax-free threshold applies where they live, so this won''t bite yet. But the habit starts now: always ask whether a figure is before or after deductions.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 1, 'Five students, five setups', 'In any class: some get a weekly allowance. Some get money only for specific things. Some get none, and earn everything themselves. Some contribute money to their household. Some have a mix that changes month to month. All five are normal. None of them is a scoreboard.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 2, 'What household income actually depends on', 'Jobs. Local cost of living. Number of people. Health. Housing costs. Timing. Luck. Almost none of it was chosen by anyone at your kitchen table — and none of it measures how clever, hardworking, or deserving anybody is.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 3, 'You''re comparing against an edit', 'Here''s why comparison always feels bad: you have complete information about your own situation — including the boring parts, the arguments, the things you go without. You have filtered information about everyone else''s — the highlights, the new stuff, the good day. Nobody posts the conversation about money at the kitchen table. The comparison was never fair.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 4, 'The part that''s actually yours', 'You don''t choose how much comes into your household. You do get some say over what happens to whatever passes through your hands: whether you track it, whether you plan, whether you spend on purpose or on reflex. That''s the part that responds to your decisions — and it''s a skill that works at any income. Someone who plans well with £5 a week will plan well with £5,000 a month.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 1, 'Income has more than one door', 'Beyond a job, money commonly arrives as gifts — birthdays, holidays. One-off jobs — babysitting, car washing, dog walking. Selling things you own — used games, clothes, tech. Small enterprises — reselling, tutoring, making something. Prizes and rewards. All of it is real income. All of it counts.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 2, 'The "found money" trap', 'People treat money they didn''t work for as less real — and spend it noticeably faster. £20 earned over four hours of dog walking feels like £20. £20 in a birthday card feels like free money. Same £20. Same buying power. Different treatment — and that''s worth catching.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 3, 'The distinction that actually matters', 'Forget where money came from. Ask whether it repeats: regular income arrives predictably — a monthly allowance, a Saturday job. Irregular income arrives unpredictably — birthday money, a one-off sale.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 4, 'The mistake almost everyone makes', 'You get £50 for your birthday. It feels like you''re now a person with £50 spare. So you start spending like it. But it was one payment, not a monthly one. Eleven months of the year, you''re short — and you never quite work out why. Regular income is what you plan around. Irregular income is what you build on top.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 5, 'Side hustles: solve something small', 'If you want to earn beyond a standard job, the useful question isn''t "what can I do?" It''s "what do people around me actually need, that I can provide?" Tutoring works because parents value it. Reselling works because people want things they can''t be bothered to find. Find a small real problem. Solve it repeatedly. Keep it legal, keep it honest, and be careful about meeting strangers — go through trusted channels and tell an adult what you''re doing.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 1, 'You can''t plan what you haven''t measured', 'Most people significantly misjudge how much money passes through their hands — usually guessing too low. Not because they''re careless. Because £3 here and £5 there is genuinely forgettable. It vanishes from memory. It doesn''t vanish from your balance.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 2, 'The two-week experiment', 'Write down everything in and everything out. Two weeks. No judging, no changing anything. That''s it. Almost everyone is surprised by the result — and it''s the foundation everything else in this course is built on. You can''t improve a number you''ve never actually seen.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 3, 'Same amount, different decision', 'Two scenarios. Both £20. £20 every month, reliably: committing £5 a month to something is reasonable. £20 once, as a gift: committing to anything ongoing is risky, because the next £20 might not come. Same amount. Opposite correct decision. The only thing that changed was reliability.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 4, 'When, not just how much', 'Having enough money doesn''t help if it arrives after you needed it. That gap — between affording something and affording it right now — is called cash flow. It''s why adults on decent incomes still get caught out by an unexpected bill. Knowing roughly when money arrives is as useful as knowing how much.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 5, 'What you''ve actually built', 'You now know where your money comes from, which sources repeat and which don''t, and roughly when each arrives. That''s not admin. That''s the whole basis for every decision in the next topic — because you can''t decide what to do with money until you know what you''ve actually got.');

-- Topic I.III slides
insert into slides (subtopic_id, "order", heading, body)
values
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 1, 'Every yes is also a no', 'When money is limited, choosing one thing means not choosing something else. That''s not pessimism. It''s arithmetic. But naming it out loud changes how the decision feels — because most people only ever count the thing they''re buying.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 2, 'Swap the question', 'Most people ask: "Can I afford this?" Yes or no. Tells you almost nothing. Better question: "What am I giving up to have this?" Now you''re comparing two real things instead of checking a balance. That''s the question that actually decides whether it''s worth it.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 3, 'Order, don''t restrict', 'Banning yourself from spending almost never lasts. Restriction feels like punishment, and punishment gets abandoned. Ordering works better. A simple version: committed — anything you''ve already promised. Saved — anything going toward a goal. Free — whatever''s left, spend it guilt-free.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 4, 'Most people run this backwards', 'The common version: spend freely, then save whatever survives. What survives is usually nothing. Not because people are irresponsible — because "whatever''s left" isn''t a plan, it''s a hope. Flipping the order is the entire trick. Same money, different sequence, completely different result.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 5, 'Watch the leaks, not just the splurges', 'Big purchases get scrutinised. Small repeated ones don''t. £2.50 most days is roughly £900 a year. Nobody decides to spend £900 on that. It happens through hundreds of separate, unmemorable choices. The point isn''t that small purchases are bad. It''s that £900 should be a decision, not an accident.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 1, 'The assumption that stops people starting', '"Saving only matters once I''ve got proper money." It''s the most common reason people don''t start — and it''s backwards.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 2, 'Consistency beats size', '£2 a week is £104 a year. £5 a week is £260 a year. Neither changes your life. But the person who saved £104 built something more valuable than the money: a habit that still works when the amounts get bigger. And the amounts usually do.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 3, 'The ingredient you have most of', 'Money left alone in a savings account earns interest — a small percentage added regularly. Then here''s the part that matters: you earn interest on the interest. That''s called compounding. Over months, it''s barely visible. Over decades, it''s the single most powerful force in personal finance. You have more time than any adult reading this. That''s not a small advantage — it''s the biggest one available. The actual maths is in Tier 3.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 4, 'What the first £50 actually buys', 'Not a thing. Options. With a small buffer: an unexpected cost is annoying. Without one: the same cost is a crisis — and you''re forced into a bad choice. Borrowing. Selling something for less than it''s worth. Asking for help you didn''t want to ask for. That''s what savings are for at your age. Not luxury. Room to manoeuvre.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 1, 'The tool', 'Need — you genuinely can''t function without it. Food, somewhere to live, warmth, getting to school, basic clothing. Want — everything else. Useful. Also blunt. Taken too literally it collapses, because almost nothing is a strict need.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 2, 'What it''s actually for', 'Not for eliminating wants. That''s a miserable and doomed project. It''s for sequencing: needs get funded first, wants get funded deliberately. The tool isn''t a rule about what you''re allowed. It''s a sorting step before you decide.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 3, 'Context decides, not the object', 'The same item sits in either category depending on the person. A laptop is a want if you do homework on paper — a need if all your coursework is submitted online. Trainers are a need if your only pair has holes — a want if it''s your fourth pair. This is exactly why comparing your spending to someone else''s doesn''t work. You see their purchase. You don''t see their context.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 4, 'The upgrade trap', 'The most common way this tool gets misused: "I need a phone." True. But that''s not the question. You have a phone, and it works. The real question is: do you need this phone rather than the one already in your pocket?'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 5, 'Say the honest version', '"I have a working one, and I want a better one." That might still be a completely fine decision. But it''s a different decision — and worth making with your eyes open rather than behind a justification that sounds like necessity.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 1, 'What you''re about to do', 'You''ve got three tools now: opportunity cost — every yes is a no. Ordering — committed, saved, free. Needs vs wants — sort before you decide. Now you use all three at once.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 2, 'There''s no single right answer', 'You''ll be given a fixed amount and more options than it covers. That''s the point. What''s being tested isn''t whether you pick the "correct" items — it''s whether you can spot what''s actually a need, name what you''re giving up, and choose in a sensible order. Two people can make different choices and both be right.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 3, 'The scenario', 'You have £25 for the month. Your options: transport to school, the only route, £12. Saving toward a £60 goal, any amount. A new game everyone''s playing, £15. Replacing broken school shoes, £18. Snacks at break, most days, about £8. You can''t have everything. Decide.');

-- Topic I.IV slides
insert into slides (subtopic_id, "order", heading, body)
values
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 1, 'It''s not a box with your name on it', 'Most people picture a vault: your specific £100, in a drawer, labelled. That''s not what happens. A bank account is a record of how much the bank owes you. Your particular notes aren''t set aside anywhere.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 2, 'Which explains something odd', 'If your money were physically stored, how could it reach someone else''s account in two seconds? It can''t. And it doesn''t. Nothing physical moves. Your record goes down by £10, theirs goes up by £10. That''s the entire transaction. Once you see money as records rather than objects, most of banking stops being mysterious.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 3, 'So where does the money actually go?', 'Banks don''t leave deposits sitting idle. They lend most of it out — to other customers, as loans and mortgages — and charge interest on it. Some of that interest comes back to you as savings interest. That''s the business model in one line: banks pay you a little for the use of your money, and charge borrowers more.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 4, 'Which is why rates move', 'Savings rates aren''t a measure of how generous your bank is feeling. They''re tied to wider economic conditions — which is why the rate on your account can change without anyone asking you.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 5, 'The two accounts you''ll actually meet', 'A current account is for everyday spending — money in, money out, comes with a debit card, and pays little or no interest. A savings account is for money you''re not spending — it pays interest, sometimes with limits on withdrawals. Most people your age start with a youth or child account, which usually can''t go below zero. You can''t spend money you don''t have — which is a feature, not a limitation.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 1, 'The card isn''t money', 'A debit card is an instruction, not a thing of value. Losing a £20 note means losing £20. Losing your card means losing a piece of plastic — the money is still on the record, and the card can be switched off.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 2, 'What happens in that one second', 'You tap. Then: the terminal messages your bank asking if you have £4.50. Your bank checks the record. It approves or declines. The record updates. All of it, usually under a second.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 3, 'Why "pending" exists', 'Sometimes a payment shows as pending for a day or two. The money is committed but the transfer hasn''t completed. That''s why your balance and your available balance can briefly disagree. Rule of thumb: trust the lower number. That''s the one that reflects what you''ve actually spent.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 4, 'Debit means your own money', 'Defining feature: a debit card spends money you already have. Balance is £30, you can spend £30. Youth accounts usually block you at zero entirely. Some adult accounts allow an overdraft — spending past zero into borrowed money, which normally costs interest or fees. Worth knowing which type you have, because it decides whether running out means "declined" or "debt".'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 5, 'Card safety, practically', 'Never share your PIN — not with friends, not with anyone phoning claiming to be your bank. Real banks never ask. Cover the keypad. Check your transactions regularly, not just when something feels wrong. Report a lost card immediately — it can be frozen in seconds. And the big one: if money is taken fraudulently and you haven''t been careless with your details, banks are generally required to refund you. Cash has no equivalent. Lost cash is just gone.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 1, 'One difference does most of the work', 'Lose £50 in cash: no record it was yours, no one to report it to, nothing to reverse. Gone. Lose your card: the account still exists, the card freezes in seconds, fraudulent transactions can usually be reversed. Records and reversibility. That''s the whole argument.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 2, 'There are actual rules behind it', 'Banks are supervised by regulators and must hold reserves. In the UK, deposits are protected by the FSCS — the Financial Services Compensation Scheme — which covers your money up to £120,000 per person, per institution, if the bank fails. Many other countries have similar schemes, with different names and different limits. That''s a legal guarantee, not a promise in an advert. Cash in a drawer has nothing remotely like it.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 3, 'The slow problem nobody notices', 'Cash at home isn''t just risky. It shrinks. Prices rise over time — that''s inflation — so the same £50 buys less each year. It doesn''t feel like losing money, because the number on the note never changes. But the number was never the point. Money in a savings account earning interest at least partly offsets this. Tier 3 covers inflation properly.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 4, 'Cash isn''t the villain', 'Honest version: cash genuinely wins at some things. It''s accepted where cards aren''t. It works when systems go down. It needs no bank account. And it makes spending feel real — handing over notes hurts more than tapping, and a lot of people genuinely spend less because of it.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 5, 'So the actual conclusion', 'Not "cash is bad." Cash is a tool for small, immediate, in-person spending. A bank account is where money should live when it isn''t being spent today. Both. For different jobs.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 1, 'The whole difference, in one line', 'Debit spends money you have. Credit spends money you don''t have yet, which you must pay back. Everything else about credit follows from that one distinction.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 2, 'Why it''s so easy to forget', 'Both cards look nearly identical. Both tap the same way. Both take about a second. Nothing at the till tells you which kind of money just moved. That''s precisely why the difference gets forgotten in the moment it matters most.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 3, 'Credit isn''t the villain either', 'Used properly, credit is genuinely useful: it spreads the cost of something large and necessary, and it builds a credit history, which later affects things like renting a home or getting a phone contract.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 4, 'The catch', 'If you don''t repay in full, you''re charged interest — often at high rates. So the thing ends up costing more than the price on the tag. Sometimes considerably more. The danger isn''t the card. It''s that credit lets you spend money you don''t have without it feeling like anything happened.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 5, 'Why you''re learning this before you can get one', 'Most countries set a minimum age for getting a credit card — commonly 18. So this isn''t a decision you face yet. But buy-now-pay-later is already on the shopping apps you use — and it runs on exactly the same principle. Get it now, pay later, consequences if you don''t. Understanding the mechanism before someone offers it to you at a checkout, under time pressure, is the entire point. Tier 2 goes into this properly.');

-- Topic I.V slides
insert into slides (subtopic_id, "order", heading, body)
values
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 1, 'Why "save money" loses', 'It''s not a willpower problem. It''s a structural one. "Save money" is vague, distant, and undefined. The thing you''re choosing between it and — those trainers, that game, this snack — is specific, immediate, and right in front of you. Vague loses to specific. Every time.'),
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 2, 'Make it a fair fight', 'Give the future thing a name, a price, and a date, and something changes. Now you''re not choosing between something specific and a vague idea. You''re choosing between two specific things. That''s a decision you can actually make.'),
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 3, 'Progress beats motivation', 'Motivation is unreliable. It shows up when it feels like it. Visible progress is what actually keeps people going. "I''m saving" gives you nothing to hold onto. "I''m at £34 of £80" — you can feel that. It''s the same reason games and apps show progress bars. Humans are far more persistent when they can see how far along they are.'),
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 4, 'Reframe what saving is', 'Saving isn''t refusing to spend. It''s deciding when, and on what. You''re not giving money up — you''re moving it from "whatever catches my attention this week" to "the thing I actually decided I wanted." That matters, because approaches that feel like punishment don''t survive contact with a bad week.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 1, 'Three tests', 'A goal that survives passes all three: specific — exactly what, at exactly what price. Achievable — the maths works with your actual income. Timed — a deadline, and a checkpoint before it. Miss one and it quietly falls apart.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 2, 'Specific: name it and price it', 'Not "save for a bike." "Save £120 for this bike." Look up the actual price — including delivery, or anything it needs to work. Goals built on a guessed number tend to collapse when reality turns out 30% higher. The specificity is doing real work: it converts a wish into something you can measure progress against.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 3, 'Achievable: do the division', 'Divide the total by what you can genuinely set aside. £120 divided by £10 a month is 12 months. If that''s too long, your honest options are: increase the rate, lower the target, extend the time, or drop it. What doesn''t work is pretending you''ll save £40 a month on £20 of income. A goal built on a number you can''t hit is designed to fail — and failing puts people off trying again.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 4, 'Timed: deadline plus checkpoint', 'No deadline means the goal drifts forever, because you''re never behind. Set an end date. Then set a checkpoint in the middle: £60 by March. That''s how you find out the plan isn''t working while there''s still time to fix it — rather than discovering it eight months in.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 5, 'Two small things that change the odds', 'Write it down. Target, rate, date. A goal that lives only in your head is easy to quietly renegotiate. Separate the money — a different account, or just a different physical place. Money mixed in with spending money gets spent, not through a decision, but because the friction was too low.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 1, 'Example A: steady income', 'Target: £80 headphones. Income: £10 a week allowance. Rate: £5 a week, keeping £5 for everyday spending. £80 divided by £5 is 16 weeks, about 4 months. Checkpoint: £40 by week 8. Easiest case, because the income is predictable. This is the basic shape: target, rate, time, checkpoint.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 2, 'Example B: irregular income', 'Target: £150 console. Income: no allowance, roughly £40 a year from occasional dog walking, roughly £60 birthday money once a year. You can''t divide by a weekly amount that doesn''t exist. So the rate becomes a proportion: save half of anything that comes in. The deadline is looser. The checkpoint is amount-based, not date-based: halfway at £75. Same method — adapted to unreliable income, not abandoned because of it.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 3, 'Example C: when the maths says no', 'Target: £400 phone. Income: £5 a week. £400 divided by £5 is 80 weeks — over a year and a half. By then the model will have been replaced and the price will have changed. This goal fails the achievable test.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 4, 'Which is a success, not a failure', 'The useful response isn''t giving up. It''s adjusting: a cheaper or second-hand model, deliberately extending the timeline, increasing income with occasional work, or choosing a different goal entirely. Finding out a goal is unrealistic at the planning stage costs you five minutes. Finding out eight months in costs you eight months.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 1, 'Your turn', 'One real goal. Yours, not an example. Run it through all three tests: specific — the exact thing, at its actual price. Achievable — the division done, honestly. Timed — a deadline, and one checkpoint.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 2, 'Small is fine', 'A £20 goal built properly teaches the method better than a £500 goal built on wishful thinking. The point isn''t the size of the target. It''s whether the maths is honest.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 3, 'What you''ve actually built this tier', 'You started this tier not knowing why you wanted things. Now you know why you spend — ads, social pressure, engineered impulse. Where money comes from, and which sources you can rely on. How to decide — opportunity cost, ordering, needs vs wants. How money is held — accounts, cards, and why records beat cash. And how to aim it — at something you actually chose.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 4, 'And what''s next', 'That''s Essentials. Three paths open from here: Application — budgeting, pricing tricks, subscriptions, buy-now-pay-later, scams. Mathematics — percentages, interest, compounding, inflation, risk. Mastery — the formulas, present and future value, behavioural finance, crypto, and building your own calculator in a coding language called Python, all by yourself. Pick whichever one you actually want.');

-- Topic I.II questions
insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 1, 1, 'mcq', 'Two jobs take the same number of hours. One is physically exhausting; the other requires a qualification few people have. The qualified job pays more. Why?', '["The employer values education over physical work","Fewer people can do it, so that skill is scarcer","Physical work is usually part-time","It''s unfair, and there''s no real reason"]'::jsonb, '1', null, null, 'Pay tracks scarcity and value, not effort. Both are real work — but if hundreds of people can do one job and only a few can do the other, that shows up in the wage. A is the common misreading: it''s not a judgement about which work matters more.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 1, 2, 'multi', 'According to this lesson, which factors actually influence how much a job pays?', '["How many people are able to do it","How many people want to do it","How much value it creates for whoever''s paying","How physically or mentally demanding it is"]'::jsonb, '[0,1,2]', null, null, 'A, B and C. Difficulty didn''t make the list — which is why exhausting jobs can pay less than comfortable ones. Unpleasant jobs sometimes pay more, but that''s option B at work (few people want it), not difficulty itself.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 1, 3, 'mcq', 'In most countries, someone aged 13 or 14 doing legal part-time work is protected by a minimum wage.', '["True","False"]'::jsonb, '1', null, null, 'This surprises almost everyone. Minimum wage protections usually begin around school-leaving age — often 15 or 16 — so below that there''s frequently no legal floor at all. It''s the single most relevant fact on this topic for someone your age, and it''s worth checking your own country''s rules before agreeing to any paid work.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 1, 4, 'mcq', 'You''re offered "£400 a month" for a job. What''s the most useful thing to ask?', '["Whether the hours are flexible","Whether that figure is before or after deductions","Whether you''ll be paid weekly or monthly","Whether there''s a probation period"]'::jsonb, '1', null, null, 'Gross and net can be very different numbers. Most people your age earn under the tax-free threshold so it may not bite yet — but the habit of asking is what stops you being caught out later, when it does.'),
  ('8f73410c-3f9e-403c-81da-5f9071ec53f3', 1, 5, 'text', 'What''s the term for the amount that actually reaches you after tax and other deductions have been taken out?', '[]'::jsonb, 'net pay', '["net pay","net","take-home pay","take home pay","take-home"]'::jsonb, null, 'Net pay, also called take-home pay. The bigger number you''re quoted first is gross pay.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 1, 1, 'mcq', 'Two students in the same class receive very different amounts of pocket money. What can you reliably conclude?', '["One family is more careful with money","One student is more trusted by their parents","Nothing about either student","One student is likely to be better at saving"]'::jsonb, '2', null, null, 'Household income depends on jobs, housing costs, family size, health, and circumstance — almost none of it chosen, and none of it a measurement of the student. It tells you about a situation, not a person.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 1, 2, 'mcq', 'Why does comparing your finances to what you see online tend to feel bad, even when nobody is lying?', '["People online are generally wealthier","You know everything about your situation, but only the highlights of theirs","Social media exaggerates prices","Money is a private topic and shouldn''t be discussed publicly"]'::jsonb, '1', null, null, 'The comparison is structurally unfair before anyone''s even lied. You''re weighing your complete picture — including the difficult parts — against someone''s edited one. Nobody posts the conversation about money at the kitchen table.'),
  ('be545cc7-4b40-4465-b2cf-ccd0d93341bd', 1, 3, 'mcq', 'Student A receives £30 a month and spends it without tracking. Student B receives £8 a month, plans it, and saves part. Who is building the more transferable skill?', '["Student A — more money means more practice managing it","Student B — planning works at any income, and incomes usually rise","Neither — the amount received is what matters","Impossible to say without knowing what they spend it on"]'::jsonb, '1', null, null, 'The amount you''re handed isn''t a skill. Planning is. Student B is building something that still works when the numbers get bigger — and for most people, they do.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 1, 1, 'mcq', 'Why do people typically spend gift money faster than money they earned?', '["Gift money is usually a smaller amount","It feels less real, because no effort was exchanged for it","There''s an unspoken expectation to spend it","Earned money is usually paid into an account instead of cash"]'::jsonb, '1', null, null, 'Same money, same buying power, filed differently by your brain. Noticing this is most of the fix — the £20 in a birthday card buys exactly as much as the £20 from four hours of dog walking.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 1, 2, 'mcq', 'What''s the most useful way to categorise money coming in?', '["By how much it is","By whether you earned it or were given it","By whether it repeats predictably or not","By whether it''s cash or transferred to an account"]'::jsonb, '2', null, null, 'Regular vs irregular is the distinction that changes your decisions. Where money came from is interesting; whether it''s coming again is what you can actually plan around.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 1, 3, 'mcq', 'You receive £50 for your birthday. What''s the risky assumption?', '["That you should spend it rather than save it","That you now have £50 spare on an ongoing basis","That it''s genuinely yours to decide about","That it should go toward one thing rather than several"]'::jsonb, '1', null, null, 'One payment doesn''t create ongoing capacity. If you start spending as though £50 arrives regularly, you''re short for the other eleven months — and it''s rarely obvious why.'),
  ('87564f3d-b2f0-48eb-92bd-ba3ba8c30625', 1, 4, 'mcq', 'What''s the most useful starting question for a side hustle?', '["What am I good at?","What pays the most per hour?","What do people around me need that I could provide?","What are other people my age doing successfully?"]'::jsonb, '2', null, null, 'Income comes from solving someone''s problem. Starting from what you''d like to sell — rather than what someone actually wants — is why most "business ideas" go nowhere, while tutoring and reselling reliably work.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 1, 1, 'mcq', 'Why do most people underestimate how much they spend?', '["They''re careless with money","Small amounts are individually forgettable but collectively significant","They genuinely spend less than they assume","Bank statements are hard to read"]'::jsonb, '1', null, null, 'It isn''t carelessness. £3 here and £5 there doesn''t stick in memory — but it does stick to your balance. That gap between what you remember and what actually happened is exactly why writing it down for two weeks is so consistently surprising.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 1, 2, 'text', 'What''s the term for the timing of money coming in and going out — as opposed to how much you have overall?', '[]'::jsonb, 'cash flow', '["cash flow","cashflow"]'::jsonb, null, 'Cash flow. It''s why someone can have enough money overall and still be stuck, because it arrives after the bill does.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 1, 3, 'mcq', 'You receive £20. In which situation does committing £5 a month to something ongoing make sense?', '["If the £20 was a one-off gift","If £20 arrives reliably every month","Either — £20 is £20","Neither — ongoing commitments should always be avoided"]'::jsonb, '1', null, null, 'Reliability decides it, not the amount. Ongoing costs need ongoing income; matching a repeating commitment to a one-off payment is one of the most common ways people end up short.'),
  ('8c8590c5-fedd-4a48-a6db-2ba25bff13eb', 1, 4, 'mcq', 'Someone earns a good income but is caught out by an unexpected bill. What''s the most likely explanation?', '["They spend more than they earn","Their money hadn''t arrived yet when the bill was due","They don''t have a savings account","The bill was larger than their monthly income"]'::jsonb, '1', null, null, 'This is cash flow. Having enough money in total doesn''t help if the timing is wrong — which is why knowing when money arrives matters as much as knowing how much.');

-- Topic I.III questions
insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 1, 1, 'mcq', 'Which question tells you more about whether a purchase is worth it?', '["\"Can I afford this?\"","\"What am I giving up to have this?\"","\"Is this cheaper than usual?\"","\"Will I still want this next month?\""]'::jsonb, '1', null, null, '"Can I afford it" has a yes/no answer that ignores everything else that money could do. B forces a comparison between two real options — which is what deciding actually means. D is a genuinely useful question too, but it''s an impulse check rather than a value one.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 1, 2, 'text', 'What''s the economic term for what you give up when you choose one option over another?', '[]'::jsonb, 'opportunity cost', '["opportunity cost"]'::jsonb, null, 'Opportunity cost. It''s the half of the price nobody puts on the label.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 1, 3, 'mcq', 'Put these in the order that makes money most likely to last: money already committed to something you''ve promised, money going toward a savings goal, money free to spend however you like.', '["Committed → Saved → Free","Saved → Committed → Free","Free → Committed → Saved","Committed → Free → Saved"]'::jsonb, '0', null, null, 'Committed, saved, then free. Most people run it backwards — spend first, save whatever survives — and what survives is usually nothing. Same money, different sequence, completely different outcome.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 1, 4, 'mcq', 'Why does "save whatever''s left at the end of the month" usually fail?', '["People lack self-discipline","Nothing is protecting the savings, so everything else reaches the money first","Saving is impractical on a small income","Most people don''t know how much they earn"]'::jsonb, '1', null, null, 'It isn''t a plan, it''s a hope. Nothing stands between your savings and everything else competing for that money — so everything else wins. Reversing the order costs nothing and changes the result entirely.'),
  ('67417bd8-9471-439a-acca-f3df60e3fb0a', 1, 5, 'num', 'If you spend £2.50 every day for a full year (365 days), roughly how much is that in total? Give your answer in pounds, to the nearest pound.', '[]'::jsonb, '912.5', null, 2.5, '£912.50 — call it £900 or so. Nobody ever decides to spend £900 on that. It happens through hundreds of separate, unmemorable choices, which is exactly why it''s invisible until you write it down.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 1, 1, 'num', 'If you save £2 a week for a year (52 weeks), how much will you have saved? Give your answer in pounds.', '[]'::jsonb, '104', null, null, '£104. Not life-changing — but the habit you built getting there is what keeps working when you''re saving £50 a week instead of £2.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 1, 2, 'text', 'What''s the word for earning interest on your interest, not just on the money you originally saved?', '[]'::jsonb, 'compounding', '["compounding","compound interest","compounding interest"]'::jsonb, null, 'Compounding. Barely visible over months, enormous over decades — which is why starting young beats starting big.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 1, 3, 'mcq', 'Why does starting to save young matter more than starting with a large amount?', '["Young people have fewer expenses","Interest rates are higher for young savers","Compounding needs time more than it needs size","Savings habits are impossible to build later in life"]'::jsonb, '2', null, null, 'Time is the ingredient you have most of right now, and it''s the one adults most often wish they''d used sooner. D is too strong — habits can be built at any age; it''s just that the years already gone can''t be recovered.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 1, 4, 'mcq', 'Your bike gets a puncture and needs £15 to fix. Why is having £50 already saved worth more than the £50 itself?', '["It shows you''re financially responsible","The interest earned covers part of the repair","You''re not forced into a worse option to raise the money","You can afford a better repair"]'::jsonb, '2', null, null, 'Without a buffer, you''re choosing between borrowing, selling something cheaply, or going without. With one, it''s just an annoying Tuesday. Small savings buy options — and options are worth more than the number suggests.'),
  ('fbefdbee-65ac-48dd-b6f4-70096da7ea9f', 1, 5, 'mcq', 'Saving small amounts is essentially pointless until you have a larger income to save from.', '["True","False"]'::jsonb, '1', null, null, 'This is the single most common reason people never start. The money saved is the smaller half of the benefit; the habit is the larger half, and the habit is what scales when the income does.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 1, 1, 'mcq', 'Is a laptop a need or a want?', '["A need — education requires one","A want — you can always use paper","It depends entirely on the person''s situation","A need if it''s for school, a want if it''s for games"]'::jsonb, '2', null, null, 'If all your coursework is submitted online, it''s a need. If you work on paper, it''s a want. The object doesn''t decide the category; the context does. D is close but still tries to sort by the object''s use rather than the person''s actual circumstances.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 1, 2, 'mcq', 'Your phone works fine. A newer model comes out and you tell yourself "I need a phone." What''s actually happening?', '["You''ve correctly identified a need","A want is being justified using language that sounds like necessity","An impulse trigger from an advert","Peer pressure from people with newer phones"]'::jsonb, '1', null, null, 'The statement is true but it''s answering the wrong question. You have a phone. The real question is whether you need this one — and the honest version, "I want a better one," might still lead you to buy it. Just with your eyes open.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 1, 3, 'mcq', 'What''s the needs-vs-wants tool actually for?', '["Making sure you don''t buy things you don''t need","Deciding which purchases are justified","Sequencing — funding needs first, then funding wants deliberately","Comparing your spending against other people''s"]'::jsonb, '2', null, null, 'It''s a sorting step, not a rulebook. Wants are completely fine. The point is that they get chosen on purpose, rather than quietly crowding out something you actually needed.'),
  ('dd99b57a-145b-4aaf-9382-64fd86a8b18b', 1, 4, 'mcq', 'Which of these is most clearly a need for the person described?', '["A second pair of school shoes, because the first pair is uncomfortable","Bus fare, when it''s the only way to get to school","A phone upgrade, because the current one is two years old","A gym membership, because exercise matters for health"]'::jsonb, '1', null, null, 'B fails the "can I function without this" test outright — no bus, no school. The others are all reasonable things to want, and D is genuinely valuable, but exercise has free alternatives in a way that a required journey doesn''t.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 1, 1, 'multi', 'You have £25 for the month. Options: (A) transport to school, only route, £12 · (B) saving toward a £60 goal, any amount · (C) new game everyone''s playing, £15 · (D) replace broken school shoes, £18 · (E) snacks at break most days, ~£8. Which of these are clearest needs?', '["Transport to school","Saving toward the £60 goal","The new game","Replacing broken school shoes","Snacks at break"]'::jsonb, '[0,3]', null, null, 'A and D. Both fail the "can I function without this" test — you can''t get to school, and broken shoes stop working. Saving is important but it isn''t a need this month; the game and snacks are real choices, just not necessities.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 1, 2, 'num', 'Same scenario (£25 for the month; A transport £12, B saving, C game £15, D shoes £18, E snacks ~£8). What is the total cost of funding both clear needs (A and D)?', '[]'::jsonb, '30', null, null, '£30 — which is £5 more than you have. That''s deliberate. Needs exceeding income is a real situation, and it''s more useful to practise than a tidy scenario where everything fits.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 1, 3, 'mcq', 'Your needs come to £30 but you only have £25. What''s the most sensible response?', '["Fund the cheaper need and skip the other entirely","Cover what''s most urgent, then close the £5 gap deliberately — delay, reduce, or earn","Abandon the plan and spend on whatever you prefer","Borrow £5 and deal with it next month"]'::jsonb, '1', null, null, 'When needs exceed income, the answer isn''t to stop planning. Cheaper shoes, delaying a week, extra work, or asking for help early rather than after it becomes a problem — all real options. D isn''t automatically wrong in life, but borrowing without a repayment plan is how a £5 gap becomes a bigger one.'),
  ('035fbb22-bec4-4619-9afe-eb4cb477903f', 1, 4, 'mcq', 'One student funds the needs, then spends the remainder on the game. Another funds the needs, then puts the remainder toward the £60 goal. Who decided correctly?', '["The second — saving should come before spending","The first — money is meant to be enjoyed","Either, provided needs came first and the trade-off was deliberate","Neither — both should have saved the full remainder"]'::jsonb, '2', null, null, 'Once needs are covered, there''s no universally correct answer. What separates a good decision from a bad one here isn''t what you chose — it''s whether you knew what you were giving up when you chose it.');

-- Topic I.IV questions
insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 1, 1, 'mcq', 'What is a bank account, most accurately?', '["A secure container holding the notes and coins you deposited","A record of how much the bank owes you","A digital copy of your money","An agreement letting the bank invest on your behalf"]'::jsonb, '1', null, null, 'It''s a record, not a container. Your particular notes aren''t set aside anywhere — which is exactly why money can move between accounts in seconds. Nothing physical travels; two records update. A is the mental image most people carry, including plenty of adults.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 1, 2, 'mcq', 'Money moves from your account to a friend''s in about two seconds. What actually happened?', '["The money was transferred electronically between the two banks'' vaults","Your record decreased and theirs increased — nothing physical moved","The bank issued a temporary credit until the cash could be moved","The money was converted into a digital form and sent"]'::jsonb, '1', null, null, 'Once you see money as records rather than objects, most of banking stops being mysterious. C and D both assume something physical needs to catch up later. It doesn''t.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 1, 3, 'mcq', 'Where does most of the money deposited in a bank actually go?', '["It stays in the bank''s reserves untouched","It''s lent out to other customers, and the bank charges them interest","It''s invested in the stock market","It''s held by the government as a guarantee"]'::jsonb, '1', null, null, 'That''s the business model in one line: banks pay you a little for the use of your money and charge borrowers more. It also explains why savings rates rise and fall — they''re tied to wider economic conditions, not the bank''s mood.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 1, 4, 'mcq', 'What''s the main difference between a current account and a savings account?', '["Savings accounts are more secure","Current accounts are for adults, savings accounts for young people","Current is built for money moving; savings is built for money sitting still, and pays interest","Savings accounts can''t be accessed without notice"]'::jsonb, '2', null, null, 'They''re designed for different jobs — movement versus stillness, which is why one pays you to leave money alone. D is true of some savings accounts, but plenty allow instant access.'),
  ('d7b1faa7-a8ea-463a-a435-8fa5d250b5a4', 1, 5, 'mcq', 'A youth or child account that can''t go below zero is more limited than an adult account, and therefore worse.', '["True","False"]'::jsonb, '1', null, null, 'It''s a feature, not a limitation. Not being able to spend money you don''t have means running out results in "declined" rather than debt — which is the safer outcome, and one plenty of adults would benefit from.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 1, 1, 'mcq', 'Why is losing your debit card less serious than losing the same amount in cash?', '["Cards are cheaper to replace than the cash is to lose","The money exists as a record, so the card can be frozen and the money stays yours","Banks insure all card losses automatically","Cards can only be used by their owner"]'::jsonb, '1', null, null, 'The card is an instruction, not the money itself. Freeze it and your balance is untouched. Lost cash has no record, no owner, and no route to recovery. D is wrong and worth knowing — a stolen card can absolutely be used, which is why you report it immediately.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 1, 2, 'mcq', 'A payment shows as "pending" on your account. What does that mean?', '["The payment was declined","It''s been committed, but hasn''t fully settled yet","The shop has made an error","You''ve been charged twice"]'::jsonb, '1', null, null, 'The money is spoken for but the transfer isn''t finished — which is why your balance and available balance can briefly disagree. Trust the lower number; that''s the one reflecting what you''ve actually spent.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 1, 3, 'mcq', 'Your balance shows £42 but your available balance shows £37. Which should you treat as your real spending money?', '["£42","£37","The average of the two","Neither — wait until they match"]'::jsonb, '1', null, null, 'Always the lower figure. The £5 difference is a pending transaction that''s already committed, even though it hasn''t finished settling.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 1, 4, 'mcq', 'Someone phones saying they''re from your bank and asks you to confirm your PIN. What should you do?', '["Give it — they''ve called you, so they''re verified","Give part of it as a compromise","Refuse — no legitimate bank ever asks for your PIN","Ask them to email the request instead"]'::jsonb, '2', null, null, 'No genuine bank will ever ask for your PIN, by phone, email, or message. Anyone who does is attempting fraud. Hang up, and if you''re unsure, call your bank back on the number printed on your card — not one they give you.'),
  ('bcd69b01-2151-42c8-8038-f38c08462713', 1, 5, 'mcq', 'If money is taken from your account fraudulently and you haven''t been careless with your details, you''re generally entitled to be refunded.', '["True","False"]'::jsonb, '0', null, null, 'This protection is one of the concrete advantages of banked money over cash — lost cash has no equivalent. It isn''t unconditional, though: being careless with your PIN or details can affect it, which is why the safety habits matter.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 1, 1, 'mcq', 'What''s the fundamental reason banked money is safer than cash?', '["Banks are large institutions and unlikely to fail","There''s a record, so things can be traced and reversed","Cash is more likely to be stolen","Banks pay interest, so the money grows"]'::jsonb, '1', null, null, 'Everything else follows from this. A record means an owner, a route to report, and a way to reverse. Cash has none of those — which is why losing it is final.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 1, 2, 'mcq', 'Why does cash kept at home lose value over time?', '["Physical notes degrade and can be refused","Prices rise, so the same amount buys less each year","Older banknote designs are gradually withdrawn","It doesn''t — £50 is always £50"]'::jsonb, '1', null, null, 'This is inflation, and it''s easy to miss precisely because the number on the note never changes. But the number was never the point — what it buys is. Money earning interest at least partly keeps up.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 1, 3, 'mcq', 'What''s a genuine advantage of cash over a card?', '["It''s protected if the bank fails","It can''t be stolen","Handing over physical notes registers more, so many people spend less","It earns interest over time"]'::jsonb, '2', null, null, 'The friction is the benefit — tapping doesn''t feel like spending in the way notes do. Cash also works when systems are down and needs no account. It''s a genuinely useful tool for the right job, which is small, immediate, in-person spending.'),
  ('e514effe-5f70-47b5-862c-22c1c2e1a8b2', 1, 4, 'mcq', 'Deposit protection schemes cover your money up to a set limit if a bank fails. What does this mean in practice?', '["The bank promises to repay you from its own funds","It''s a legal guarantee, backed by regulation, up to a specified amount","Your money is insured privately by the bank","All of your money is protected regardless of amount"]'::jsonb, '1', null, null, 'It''s a legal guarantee rather than a promise in an advert — which is a meaningful difference. D is the common misconception: the protection has a ceiling, and the exact figure varies by country and changes over time.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 1, 1, 'mcq', 'What''s the core difference between a debit card and a credit card?', '["Credit cards have stronger fraud protection","Debit spends money you have; credit spends money you must pay back","Credit cards can be used internationally, debit cards can''t","Debit cards are for everyday spending, credit cards for large purchases"]'::jsonb, '1', null, null, 'That single distinction explains everything else about credit — the risks, the benefits, and why it needs more care. D describes how people often use them, but it isn''t what makes them different.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 1, 2, 'mcq', 'Why is credit risky if you don''t repay in full?', '["Your card is withdrawn","You''re charged interest, so the item ends up costing more than its price","It becomes harder to use the card again","The purchase can be reversed by the lender"]'::jsonb, '1', null, null, 'Interest is the cost of borrowing, and on credit cards it''s often high. Repay in full and it costs nothing; carry a balance and the sticker price stops being the real price.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 1, 3, 'mcq', 'Using credit is always a bad financial decision.', '["True","False"]'::jsonb, '1', null, null, 'Credit isn''t the villain. It spreads the cost of something large and necessary, and it builds a credit history that later affects things like renting a home or getting a phone contract. The danger isn''t the card — it''s that credit lets you spend money you don''t have without it feeling like anything happened.'),
  ('35318b34-1b76-4329-9655-6b20e790b460', 1, 4, 'mcq', 'You''re buying £60 trainers online and see "or 3 payments of £20." Why is this worth pausing on?', '["It always costs more in total","It''s borrowing — money you don''t have yet, with consequences if you don''t repay","It''s only available to people over 18","It damages your credit history automatically"]'::jsonb, '1', null, null, 'Splitting it up makes £60 feel like £20, which is precisely the point of the design. It might still be a fine choice — but it should be recognised as borrowing before you tap, not afterwards.');

-- Topic I.V questions
insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 1, 1, 'mcq', 'Why does "just save money" usually fail?', '["People lack the discipline to stick to it","It''s vague, and it competes against specific, immediate temptations","Saving is impractical on a small income","There''s no reward for doing it"]'::jsonb, '1', null, null, 'It''s structural, not a character flaw. A vague future benefit loses to a concrete present one almost every time — until you make the future one just as specific. A is the explanation people usually reach for, and it''s the least useful, because it suggests the fix is trying harder.'),
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 1, 2, 'mcq', 'What does naming a goal and attaching a price to it actually change?', '["It makes you feel more committed","It turns the choice into two specific things, rather than something specific versus something vague","It makes the goal achievable faster","It creates accountability to other people"]'::jsonb, '1', null, null, 'You''re levelling the playing field. Now both options are real and comparable, and the future one can actually win the argument.'),
  ('2d96ed44-cbe5-45f7-9a96-7143c4a40d5b', 1, 3, 'mcq', 'What keeps people going more reliably than motivation?', '["Willpower","Rewards from other people","Visible progress","Fear of running out of money"]'::jsonb, '2', null, null, '"I''m at £34 of £80" gives you something to hold onto on the days motivation doesn''t show up — which is exactly why progress bars exist in every app you use.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 1, 1, 'mcq', 'Which of these goals passes the "specific" test?', '["Save as much as I can this year","Save up for a bike","Save £120 for this bike by June","Stop wasting money on things I don''t need"]'::jsonb, '2', null, null, 'Exact item, exact price, exact date. The others can''t be measured, which means you can never tell whether you''re on track — and a goal you can''t track is one you''ll drift away from without noticing.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 1, 2, 'num', 'Your target is £90 and you can save £6 a month. How many months will it take?', '[]'::jsonb, '15', null, null, '£90 ÷ £6 = 15 months. That might be too long for you — and if so, the honest response is to adjust the target, the rate, or the timeline. Not to pretend you''ll save more than you can.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 1, 3, 'multi', 'Your goal''s maths says it will take longer than you want. Which of these are honest ways to respond?', '["Increase how much you save each month","Choose a cheaper target","Extend the deadline deliberately","Assume you''ll find extra money along the way","Drop the goal and choose a different one"]'::jsonb, '[0,1,2,4]', null, null, 'A, B, C and E are all legitimate. D is the one that fails — a goal built on money you''re hoping will appear is designed to collapse, and collapsing puts people off trying again.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 1, 4, 'mcq', 'Why set a checkpoint partway through a goal?', '["To break the goal into more manageable pieces","To find out early if the plan isn''t working, while there''s still time to adjust","To create a moment worth celebrating","To check whether the price has changed"]'::jsonb, '1', null, null, 'Without one, you only discover you''re behind at the deadline — when it''s too late to do anything about it. A midpoint check turns a failure into an adjustment. A is a real benefit too, but it''s the smaller one.'),
  ('8fc2f64d-7dbe-49e7-9372-2d807a14a148', 1, 5, 'mcq', 'You''ve built a goal: £45, saving £5 a week, checkpoint at £25. What are the two things most likely to make it stick?', '["Telling friends about it and checking progress daily","Writing it down, and keeping the money separate from everyday spending","Choosing a shorter deadline and a higher rate","Setting up an automatic transfer and forgetting about it"]'::jsonb, '1', null, null, 'Written down, it can''t be quietly renegotiated in your head. Kept separate, it doesn''t get spent by accident — because money mixed in with spending money gets spent without any decision ever being made. D is genuinely good advice for adults with accounts that support it.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 1, 1, 'num', 'Target: £80 headphones. You save £5 a week. How many weeks will it take?', '[]'::jsonb, '16', null, null, '£80 ÷ £5 = 16 weeks, roughly four months. Doing this division before you start is what tells you whether the goal is realistic — or whether something needs to change.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 1, 2, 'num', 'Using the example above, at what amount would the halfway checkpoint sit?', '[]'::jsonb, '40', null, null, '£40, which lands at week 8. If you''re well short of it by then, you''ve found out with two months still available to adjust.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 1, 3, 'mcq', 'You have no regular allowance and your income arrives unpredictably. How should you set a savings rate?', '["Estimate a weekly figure and treat it as fixed","Save a proportion of whatever arrives, and measure progress by amount rather than date","Wait until you have a regular income before setting goals","Set the goal, then borrow to cover the gaps"]'::jsonb, '1', null, null, 'The method adapts rather than breaking. When you can''t predict when money arrives, you commit to a share of it instead of a fixed amount — and you track progress by reaching amounts, not by hitting dates.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 1, 4, 'num', 'Target: £400 phone. You can save £5 a week. How many weeks would this take?', '[]'::jsonb, '80', null, null, '80 weeks — over a year and a half. By then the model will likely have been replaced and the price will have changed. This goal fails the achievable test, and finding that out now took about ten seconds.'),
  ('e279ae29-62ee-48d8-b5b8-b9c4908a298c', 1, 5, 'mcq', 'Your maths shows a goal would take 18 months, by which point the item will have changed. What''s the best response?', '["Save anyway and reassess later","Conclude that goal-setting doesn''t work for your situation","Adjust — a cheaper target, a longer timeline, or more income","Borrow the money and repay it from your savings"]'::jsonb, '2', null, null, 'Discovering this at the planning stage is the system working, not failing. Five minutes of maths just saved you eight months of saving toward something that was never going to work.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 1, 1, 'multi', 'Which three tests should every goal pass?', '["Specific — the exact thing, at its actual price","Achievable — the maths works with your real income","Impressive — big enough to be worth the effort","Timed — a deadline, plus a checkpoint"]'::jsonb, '[0,1,3]', null, null, 'A, B and D. Size isn''t a test — a £20 goal built properly teaches the method better than a £500 goal built on wishful thinking.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 1, 2, 'mcq', 'Why is a small, well-built goal better practice than a large, unrealistic one?', '["Small goals are quicker to complete","You''re learning a method, and it only works if the maths is honest","Large goals are rarely achievable at any age","Small purchases matter more day to day"]'::jsonb, '1', null, null, 'You''re building a skill, not just saving for one item. A £20 goal you actually finish teaches you something that works at £2,000. An unrealistic goal teaches you that goals don''t work.'),
  ('16236d60-045e-41e7-b5b2-bf994927e0af', 1, 3, 'mcq', 'What''s the single most common reason goals fail?', '["Unexpected costs come up","The maths was never realistic to begin with","People lose interest in what they were saving for","Prices rise before the goal is reached"]'::jsonb, '1', null, null, 'Most failed goals were never achievable at the rate they were set — the failure happened at the planning stage, not the saving stage. All of the others do happen; this one happens most, and it''s the only one you can fully prevent before you start.');
