-- Real Tier 2 content for Topic II.III — Subscriptions & Recurring Costs.
-- Same pattern as Tier 1: fixed UUIDs for topic/subtopic rows (safe to
-- re-run), slides/questions are a single-shot content load (no on-conflict
-- guard -- do not paste this file twice).

insert into topics (id, tier, "order", title, video_url)
values ('cccc3aa9-eaa0-444f-9458-4baf2586319a', 2, 3, 'Subscriptions & Recurring Costs', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 'cccc3aa9-eaa0-444f-9458-4baf2586319a', 'How Small Payments Add Up', 1),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 'cccc3aa9-eaa0-444f-9458-4baf2586319a', 'Free Trials', 2),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 'cccc3aa9-eaa0-444f-9458-4baf2586319a', 'Auditing Your Subscriptions', 3),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 'cccc3aa9-eaa0-444f-9458-4baf2586319a', 'Cancelling and Managing', 4)
on conflict (id) do nothing;

insert into slides (subtopic_id, "order", heading, body)
values
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 1, 'The multiplier nobody applies', '£4.99 a month is genuinely small. That''s the point — it''s priced to feel like nothing. × 12 = £59.88 a year. Same money. One of those numbers you''d think about; the other you wouldn''t.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 2, 'Now stack them', 'Three subscriptions at £5, £8 and £4: Monthly: £17 — noticeable, but manageable. Yearly: £204. Nobody decides to spend £204. They make three small decisions months apart and never add them together, because the bill never arrives as one number.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 3, 'Why the monthly framing wins', 'Pricing something monthly isn''t just convenient — it changes what you''re comparing it against. "£5 a month" gets weighed against a coffee. "£60 a year" gets weighed against something you''d actually save for. Identical cost, completely different judgement, and companies know exactly which framing produces more sign-ups.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 4, 'Always convert before deciding', 'Multiply by 12 before you subscribe, not after. Then ask the real question: would I pay this as one annual payment, up front, today? If yes, subscribe with confidence. If the answer is clearly no, the monthly framing was doing the persuading, not the product.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 1, 'A free trial is a countdown', 'It''s not a gift. It''s a scheduled first payment with a delay in front of it. That''s not automatically bad — plenty of trials are genuinely useful. But it''s worth naming what it actually is, because the word "free" does a lot of work in hiding the structure.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 2, 'Why they ask for card details up front', 'A trial that required you to actively opt in at the end would convert far worse than one that charges unless you opt out. That''s the entire design. Default bias — most people go with whatever happens if they do nothing, and here, doing nothing means paying. Taking your card details at the start isn''t about verification. It''s about which side of that default you land on.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 3, 'The forgetting is designed in', 'Sign-up takes thirty seconds and happens when you''re interested. The charge lands thirty days later, when you''ve forgotten, on a random Tuesday, for an amount small enough not to prompt a check. Every element of that timing works against you noticing.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 4, 'Two things that actually work', 'Set a reminder for two days before it ends — the moment you sign up, not later. Decide the cancel date at sign-up, not at the end. Deciding under no pressure produces a different answer than deciding on the day, when you''ve been using the thing for a month. Neither requires willpower. Both just move the decision to a moment where you''re thinking clearly.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 1, 'Almost nobody has done this', 'Not "roughly knows." Actually sat down and listed every recurring payment, with its amount and renewal date. It takes about fifteen minutes and it is reliably surprising — usually because of something that''s been charging quietly for months.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 2, 'How to actually find them', 'Bank or app statements, scanning for the same amount repeating on roughly the same date each month. That''s the pattern to look for. Also worth checking: app store subscription lists, and your email for "your receipt" or "renewal" messages. Some recurring payments never appear as an obvious subscription anywhere.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 3, 'Sort into three piles', 'As you list each one: use it regularly — keep, no guilt. Barely use it — the real decision. Forgot it existed — cancel today. That middle pile is where the money is. It''s easy to cancel something you''d forgotten and easy to keep something you love. The middle takes an actual decision, which is why it survives audits.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 4, 'Convert each one to its annual cost', 'Next to each subscription, write the yearly number. Then ask: would I pay that, today, as a single payment? Not "is this nice to have" — that''s always yes, which is why it''s a useless question. The annual figure is what turns a vague feeling into a decision you can actually make.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 1, 'Sign-up is one click, cancelling rarely is', 'Notice the asymmetry next time. Subscribing takes seconds. Cancelling often takes several screens, a survey about why you''re leaving, and a final offer. That''s not incompetence. It''s designed friction, and knowing it''s deliberate makes it much easier to push through rather than deciding it''s too much hassle.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 2, 'Dark patterns', 'The technical term for interfaces designed to steer you against your own interest is dark patterns. Common ones: burying cancellation deep in settings, greying out the cancel button so it looks disabled, framing it as "are you sure you want to lose all your benefits", or offering a discount right at the moment you''re leaving. Recognising it as a technique — rather than as your own indecision — is most of the defence.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 3, 'Cancelling usually doesn''t mean losing access today', 'Most subscriptions run to the end of the period you''ve already paid for. So cancelling on day 3 of a month usually means you keep access until day 30 and simply aren''t charged again. That matters, because "I''ll cancel later so I don''t waste what I''ve paid" keeps a lot of subscriptions alive that shouldn''t be. Cancel when you decide. Use the rest of the time you''ve paid for.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 4, 'Keep the receipt', 'Screenshot the confirmation, or keep the cancellation email. If a payment appears afterwards, that record is the difference between a two-minute fix and an argument you can''t win. Rare, but it happens — and it costs nothing to keep.');

insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 2, 1, 'num', 'A subscription costs £3.50 a month. How many pounds is that over a full year?', '[]'::jsonb, '42', null, null, '£3.50 × 12 = £42. Same money either way — but £3.50 is a number you''d wave through and £42 is one you''d think about.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 2, 2, 'num', 'Someone pays for three subscriptions: £6, £9 and £2.50 a month. How many pounds is that in total over a year?', '[]'::jsonb, '210', null, null, '£6 + £9 + £2.50 = £17.50 a month, × 12 = £210. Nobody decides to spend £210 — they make three small decisions months apart and never add them together, because the bill never arrives as one number.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 2, 3, 'mcq', 'Why does pricing something monthly rather than annually increase sign-ups?', '["Monthly payments are genuinely cheaper overall","It changes what the cost gets compared against","People can cancel monthly plans more easily","Annual plans require more commitment"]'::jsonb, '1', null, null, '"£5 a month" gets weighed against a coffee. "£60 a year" gets weighed against something you''d save for. Identical cost, completely different judgement — and companies know exactly which framing converts better.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 2, 4, 'mcq', 'What''s the most useful question to ask before subscribing to something?', '["Can I afford this each month?","Would I pay the yearly total, up front, today?","Is there a cheaper alternative?","How long is the minimum contract?"]'::jsonb, '1', null, null, 'The annual figure is what turns a vague feeling into a decision. If the answer is yes, subscribe with confidence — if it''s clearly no, the monthly framing was doing the persuading, not the product.'),
  ('1024ac62-b6e7-451a-84f2-ad81b8a87db7', 2, 5, 'mcq', 'A subscription that costs less per month than a single takeaway is too small to be worth calculating annually.', '["True","False"]'::jsonb, '1', null, null, 'That comparison is exactly the one the monthly framing invites, and it''s how small costs escape examination. £4.99 a month is £59.88 a year — genuinely worth a decision, and the multiplication takes two seconds.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 2, 1, 'mcq', 'What is a free trial, structurally?', '["A free sample with no obligation","A scheduled first payment with a delay in front of it","A discount on the first month","A test period that ends automatically"]'::jsonb, '1', null, null, 'D is the assumption that costs people money — most trials end by charging you, not by stopping. Naming the structure honestly is what makes the reminder feel necessary.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 2, 2, 'text', 'What''s the term for people''s tendency to go with whatever happens if they take no action?', '[]'::jsonb, 'default bias', '["default bias","default effect","status quo bias","defaults"]'::jsonb, null, 'Default bias. It''s why trials take your card up front — the question isn''t whether you''ll decide to subscribe, it''s which side of "doing nothing" the payment sits on.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 2, 3, 'mcq', 'Why do free trials ask for card details before the trial starts?', '["To verify your identity","So that doing nothing results in payment rather than cancellation","To prevent people signing up repeatedly","Because payment processors require it"]'::jsonb, '1', null, null, 'A trial you had to actively opt into at the end would convert far worse than one that charges unless you opt out. Taking the card at the start is what makes the default a payment. A and C are real reasons companies sometimes give, but neither explains the timing.'),
  ('8af42a7b-c2de-438d-8ae6-b015ed3cfaa2', 2, 4, 'mcq', 'Which is most likely to stop an unwanted trial converting into a paid subscription?', '["Choosing trials from companies you trust","Setting a reminder for two days before it ends, at the moment you sign up","Only starting trials when you have spare money","Reading the terms carefully before signing up"]'::jsonb, '1', null, null, 'The trial is designed around you forgetting, so the fix is to make forgetting impossible rather than to try harder to remember. Doing it at sign-up matters — deciding under no pressure produces a different answer than deciding on the day.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 2, 1, 'mcq', 'When looking through a bank statement for subscriptions, what''s the pattern to look for?', '["Any payment above a certain amount","The same amount repeating on roughly the same date each month","Payments to companies you don''t recognise","Payments made late at night"]'::jsonb, '1', null, null, 'Regularity is the signature, not size or unfamiliarity. C catches some but misses the ones you do recognise and forgot you were still paying for — which is usually where the money is.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 2, 2, 'mcq', 'When sorting subscriptions into "use it regularly", "barely use it" and "forgot it existed", which pile takes the most actual deciding?', '["Use it regularly","Barely use it","Forgot it existed","They''re equally difficult"]'::jsonb, '1', null, null, 'The other two decide themselves — keep the one you love, cancel the one you''d forgotten. The middle pile requires an actual judgement, which is precisely why it survives audits and quietly keeps costing money.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 2, 3, 'mcq', 'Why write the annual cost next to each subscription when auditing?', '["It makes the list easier to sort","It turns \"is this nice to have?\" into a decision you can actually make","Annual plans are usually cheaper","It shows which ones renew soonest"]'::jsonb, '1', null, null, '"Is this nice to have?" is always yes, which makes it a useless question. "Would I pay £84 for this today, as one payment?" is answerable — and it''s the same money.'),
  ('5fe03f52-e31d-46f9-be31-ba6c4a283952', 2, 4, 'multi', 'Where might a recurring payment be hiding that isn''t obvious on a bank statement?', '["App store subscription lists","Emails with \"your receipt\" or \"renewal\" in them","The company''s own account settings page","Your browser history"]'::jsonb, '[0,1,2]', null, null, 'A, B and C are all places a recurring charge leaves a trace. Browser history shows what you visited, not what you''re paying for — and plenty of subscriptions were set up on a device you no longer use.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 2, 1, 'text', 'What''s the term for interface design deliberately built to steer users against their own interests?', '[]'::jsonb, 'dark patterns', '["dark patterns","dark pattern","deceptive design","deceptive patterns"]'::jsonb, null, 'Dark patterns. Recognising the difficulty as a technique — rather than as your own indecision — is most of the defence against it.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 2, 2, 'multi', 'Which of these are dark patterns used to discourage cancellation?', '["Burying the cancel option deep in settings","Greying out the cancel button so it looks disabled","Requiring a password to access account settings","Offering a discount at the exact moment you try to leave","Framing cancellation as \"losing all your benefits\""]'::jsonb, '[0,1,3,4]', null, null, 'A, B, D and E all exist to make you stop. C is genuine security — it protects your account rather than the company''s revenue, which is the distinction worth being able to make.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 2, 3, 'mcq', 'You''re three days into a month you''ve already paid for and decide to cancel. What usually happens?', '["You lose access immediately and forfeit the rest of the month","You keep access until the period ends and simply aren''t charged again","You receive a refund for the unused days","The cancellation takes effect at the end of the next month"]'::jsonb, '1', null, null, 'Most subscriptions run to the end of the paid period. This matters because "I''ll cancel later so I don''t waste what I''ve paid" keeps a lot of subscriptions alive that shouldn''t be — you can cancel when you decide and still use the time.'),
  ('4c27bc20-ddcd-4c07-9fce-a188851ec516', 2, 4, 'mcq', 'Why keep a screenshot or email confirming a cancellation?', '["Some companies require proof to complete the cancellation","If a payment appears afterwards, it''s the difference between a quick fix and an argument you can''t win","It''s needed to claim a refund","It proves when you signed up"]'::jsonb, '1', null, null, 'Rare, but it happens — and the record costs nothing to keep. Without it you''re asserting something you can''t demonstrate, which is a much weaker position than it sounds.');
