-- Real Tier 2 content for Topic II.I — Budgeting Basics.
-- Same pattern as Tier 1: fixed UUIDs for topic/subtopic rows (safe to
-- re-run), slides/questions are a single-shot content load (no on-conflict
-- guard -- do not paste this file twice).

insert into topics (id, tier, "order", title, video_url)
values ('ce63ffcf-82e9-4c24-9420-cfc58af15dc4', 2, 1, 'Budgeting Basics', null)
on conflict (id) do nothing;

insert into subtopics (id, topic_id, title, "order")
values
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 'ce63ffcf-82e9-4c24-9420-cfc58af15dc4', 'Income vs Spending: Seeing the Full Picture', 1),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 'ce63ffcf-82e9-4c24-9420-cfc58af15dc4', 'Fixed Costs vs Flexible Costs', 2),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 'ce63ffcf-82e9-4c24-9420-cfc58af15dc4', 'Building a Simple Budget', 3),
  ('e5294bb8-a2ce-4df5-9740-5d0d5cbc70d9', 'ce63ffcf-82e9-4c24-9420-cfc58af15dc4', 'Practice: Budget a Real Scenario', 4)
on conflict (id) do nothing;

insert into slides (subtopic_id, "order", heading, body)
values
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 1, 'Most people only watch one side', 'Ask someone whether they''re good with money and they''ll usually talk about spending — what they cut back on, what they resisted buying. Almost nobody can tell you, without checking, what actually came in last month. That''s the problem. You can be excellent at spending less and still have no idea whether you''re ahead or behind, because you''re only looking at half the picture.'),
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 2, 'A budget is just both numbers in one place', 'That''s genuinely it. Money in, money out, written down where you can see them together. Everything else — categories, apps, spreadsheets, rules — is decoration on top of that one idea. Plenty of people run perfectly good budgets on the back of a page.'),
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 3, 'The gap is the only number that matters', 'In minus out. That''s your gap. Positive means you have room — to save, to plan, to absorb something unexpected. Negative means the maths isn''t working, and no amount of being careful will fix it until either income rises or spending falls. Most people never calculate this. They just have a vague feeling about it, and vague feelings are almost always wrong in the optimistic direction.'),
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 4, 'Why writing it down beats remembering', 'Your memory is not neutral about your own spending. Big, unusual purchases stick. Small, frequent ones vanish. That means the picture in your head is systematically biased — it over-remembers the £30 thing you agonised over and under-remembers ten £3 things you didn''t think about at all. Writing it down isn''t about discipline. It''s about not relying on a source you already know is unreliable.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 1, 'Two kinds of money going out', 'Fixed — roughly the same every time, arrives whether you think about it or not. A subscription, a bus pass, a phone plan. Flexible — changes based on what you decide. Snacks, going out, things you buy because you fancied them.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 2, 'Why the split matters more than it looks', 'Fixed costs are decided once and then repeat automatically. Flexible costs are decided every single time. That means they need completely different responses. You reduce a fixed cost by making one decision — cancel it, downgrade it, switch it. You reduce a flexible cost by making the same decision over and over, which is far harder to sustain. If you want to spend less, the fixed side is almost always the easier win, and it''s the one people look at last.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 3, 'Fixed doesn''t mean unchangeable', 'The word "fixed" makes these feel permanent. They aren''t — they''re just automatic. A subscription you''ve had for a year isn''t a law of nature. It''s a decision you made once and haven''t revisited. Most people have at least one.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 4, 'Fixed costs eat your floor', 'Here''s the part worth understanding properly: every fixed cost lowers the amount you have available before you''ve decided anything. If £15 a month leaves automatically, you don''t have your full income to work with — you have your income minus £15, permanently, until you change it. That''s why fixed costs deserve more scrutiny than their size suggests. They''re not competing with your other choices. They''re removed before the choosing starts.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 1, 'The method, in four steps', 'Write down what comes in, and how reliably. List your fixed costs. Subtract — what''s left is what you''re actually deciding about. Split that remainder deliberately: some saved, some free to spend. That''s the whole thing. It works at £10 a week and it works at £4,000 a month.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 2, 'Worked example: £40 a month', 'Income: £40 (£10 a week, reliably). Fixed: one £6 subscription. Remainder: £34. Split: £14 to a savings goal, £20 free to spend. Notice the order — saving comes out of the remainder before the free spending, not after. Do it the other way and the saving is whatever survives, which is usually nothing.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 3, 'Worked example: irregular income', 'No regular allowance. Roughly £25 some months from odd jobs, sometimes nothing. You can''t budget a fixed amount you don''t reliably get. So the plan becomes a rule instead of a number: whenever money arrives, half of it goes to saving before anything else. Same method, adapted. The structure survives even when the income doesn''t cooperate.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 4, 'A budget is a prediction, not a promise', 'Your first budget will be wrong. That''s normal and not a failure — you''re estimating, and estimates improve with data. The useful move is to check it after a month against what actually happened, and adjust. A budget you revise three times is working. A budget you wrote once and never looked at again isn''t a budget, it''s a wish.'),
  ('e5294bb8-a2ce-4df5-9740-5d0d5cbc70d9', 1, 'What you''re about to do', 'You''ll be given an income, some fixed costs, and a set of choices, and you''ll build the budget yourself using the four-step method. There''s no single correct answer — different priorities produce different budgets, and that''s fine. What''s being tested is whether the maths holds together, and whether saving got its share before the free spending did.');

insert into questions (subtopic_id, tier, "order", question_type, question_text, options, correct_answer, accepted_answers, tolerance, explanation)
values
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 2, 1, 'mcq', 'What''s the minimum a budget actually needs to contain?', '["A breakdown of spending by category","Money coming in and money going out, in the same place","A savings target for each month","A record of every individual purchase"]'::jsonb, '1', null, null, 'Both numbers together — that''s the whole idea. Categories, targets and detailed records are all useful additions, but each is decoration on top of the one thing that makes it a budget rather than a list.'),
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 2, 2, 'mcq', 'Someone tracks their spending carefully every month but never notes what they earn. What can''t they answer?', '["Which category they spend most on","Whether they''re spending more than they receive","How much they spent last week","Whether their spending is rising"]'::jsonb, '1', null, null, 'They can answer everything about spending and nothing about their position. Being excellent at one side of the equation tells you nothing about the gap, and the gap is the number that decides whether the plan works.'),
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 2, 3, 'mcq', 'Why is your memory an unreliable guide to your own spending?', '["People deliberately avoid thinking about money","Large purchases are memorable and small frequent ones aren''t","Most spending happens without you noticing at all","People generally overestimate what they spend"]'::jsonb, '1', null, null, 'The bias has a direction. One £30 purchase you agonised over stays with you; ten £3 purchases you didn''t think about disappear. So the picture in your head is systematically wrong in a predictable way — which is exactly why writing it down works. D is the common assumption and it''s backwards: people usually underestimate.'),
  ('d2862cbf-5c1d-4522-9b15-88f74c9f9704', 2, 4, 'mcq', 'If your income is higher than your spending, being more careful with money will still improve your position.', '["True","False"]'::jsonb, '0', null, null, 'A positive gap gives you room — to save, to plan, to absorb something unexpected — and widening it gives you more. The point of calculating the gap isn''t that a positive one means stop thinking; it''s that a negative one can''t be fixed by care alone. That takes income rising or spending falling.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 2, 1, 'mcq', 'What makes a cost "fixed"?', '["It can''t be changed","It''s essential rather than optional","It repeats automatically at roughly the same amount","It''s paid by direct debit"]'::jsonb, '2', null, null, 'Fixed means automatic, not unchangeable — that''s the most common misreading, and it''s the reason old subscriptions survive for years. A fixed cost is a decision you made once and haven''t revisited, which is very different from one you can''t revisit.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 2, 2, 'mcq', 'Why is reducing a fixed cost usually easier than reducing a flexible one?', '["Fixed costs are normally larger","One decision handles it, rather than the same decision repeatedly","Flexible costs are essential","Fixed costs have no cancellation fees"]'::jsonb, '1', null, null, 'Cancel a subscription once and it stays cancelled. Spend less on snacks and you have to decide again tomorrow, and the day after. Sustaining a repeated decision is far harder than making a single one — which is why the fixed side is the easier win, and the one people examine last.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 2, 3, 'multi', 'Which of these would normally count as fixed costs?', '["A monthly music subscription","A weekly bus pass","Money spent at the shop on the way home","A phone contract","A birthday present for a friend"]'::jsonb, '[0,1,3]', null, null, 'A, B and D repeat automatically at a predictable amount. C and E vary each time and depend on a decision you make in the moment — that''s what makes them flexible, not their size.'),
  ('8a342e23-e22a-404e-a642-eb17ca846bd6', 2, 4, 'num', 'Someone receives £50 a month. £12 of that leaves automatically for fixed costs. How many pounds are they actually deciding about each month?', '[]'::jsonb, '38', null, null, '£50 − £12 = £38. The £12 was removed before any choosing started, which is the point: fixed costs don''t compete with your other decisions, they shrink the pot those decisions are made from.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 2, 1, 'mcq', 'In the four-step budgeting method, what comes immediately after subtracting fixed costs from income?', '["Recording what you spent last month","Splitting the remainder between saving and free spending","Setting a savings target","Cancelling any unnecessary subscriptions"]'::jsonb, '1', null, null, 'The remainder is what you''re genuinely deciding about, and the split is the decision. Everything before it was arithmetic; this is the only step where preference comes in.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 2, 2, 'num', 'Someone receives £60 a month and has £9 of fixed costs. They put £16 toward a savings goal. How many pounds are left as free spending?', '[]'::jsonb, '35', null, null, '£60 − £9 = £51 remainder; £51 − £16 = £35 free. Notice the saving came out of the remainder before the free spending was worked out — reverse the order and the saving becomes whatever survives, which is usually nothing.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 2, 3, 'mcq', 'Why does saving come out of the remainder before free spending is calculated, rather than after?', '["It makes the arithmetic simpler","Nothing protects savings if everything else reaches the money first","Banks require it","Free spending is less important than saving"]'::jsonb, '1', null, null, '"Save whatever''s left" isn''t a plan, it''s a hope — and everything else competing for that money gets there first. Same money, same total, different order, completely different outcome. D isn''t the reasoning: free spending is a legitimate part of the plan, it just goes second.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 2, 4, 'mcq', 'Someone has no regular allowance and earns unpredictable amounts from occasional work. How should they budget?', '["Wait until they have a regular income before budgeting","Estimate a monthly average and treat it as fixed","Use a rule — a set share of whatever arrives goes to saving first","Save everything that comes in and spend nothing"]'::jsonb, '2', null, null, 'The method adapts rather than breaking. When you can''t predict a number, you commit to a proportion instead — the structure survives even when the income doesn''t cooperate. B fails because a month with nothing coming in breaks a plan built on an average.'),
  ('4419cd3c-b137-4fd4-b362-e4bd8a9867be', 2, 5, 'mcq', 'A budget that turns out to be wrong after the first month means the method didn''t work.', '["True","False"]'::jsonb, '1', null, null, 'A first budget is an estimate, and estimates improve with data. A budget you revise three times is working exactly as intended. The one that isn''t working is the one you wrote once and never looked at again.'),
  ('e5294bb8-a2ce-4df5-9740-5d0d5cbc70d9', 2, 1, 'num', 'A student receives £45 a month. Their fixed costs are a £7 subscription and a £11 travel pass. How many pounds are left as the remainder to split?', '[]'::jsonb, '27', null, null, '£7 + £11 = £18 of fixed costs. £45 − £18 = £27. That £27 is the only part they''re genuinely deciding about — the rest left automatically.'),
  ('e5294bb8-a2ce-4df5-9740-5d0d5cbc70d9', 2, 2, 'mcq', 'A student has £27 left after fixed costs. They want to save toward a £54 goal and reach it in three months. How much do they need to set aside each month, and does it fit?', '["£9 a month — fits comfortably","£18 a month — fits, leaving £9 free","£27 a month — fits, leaving nothing free","£54 a month — doesn''t fit"]'::jsonb, '1', null, null, '£54 ÷ 3 = £18 a month, and £27 − £18 = £9 left as free spending. It fits, but tightly — worth knowing before committing rather than discovering in week two.'),
  ('e5294bb8-a2ce-4df5-9740-5d0d5cbc70d9', 2, 3, 'mcq', 'A student''s income is £30 a month. Their fixed costs total £34. What does the budget tell them?', '["They need to be more careful with flexible spending","Their fixed costs alone exceed their income — something structural has to change","They should save less each month","The budget has been calculated incorrectly"]'::jsonb, '1', null, null, 'There''s no flexible spending left to be careful with — the automatic costs already exceed what comes in. This can only be fixed by reducing a fixed cost or increasing income. A is the instinctive answer and it''s the one that can''t work here, which is exactly why calculating the gap matters.'),
  ('e5294bb8-a2ce-4df5-9740-5d0d5cbc70d9', 2, 4, 'multi', 'A student''s fixed costs are more than they can afford. Which of these are genuine ways to fix that?', '["Cancel or downgrade a subscription","Spend less on snacks each week","Find occasional paid work to increase income","Switch to a cheaper travel option","Save a smaller amount each month"]'::jsonb, '[0,2,3]', null, null, 'A, C and D each change either the fixed costs or the income — the two things actually causing the problem. B and E adjust parts of the budget that the fixed costs have already consumed, so neither closes the gap.');
